IF DB_ID(N'AW_SANDBOX') IS NULL CREATE DATABASE AW_SANDBOX COLLATE Latin1_General_CS_AS;  -- como el real (CS_AS por columna y por defecto)
GO
ALTER DATABASE AW_SANDBOX SET COMPATIBILITY_LEVEL = 130;
GO
