SET NOCOUNT ON;
-- Producto 10: cambia la descripción (BEZ1) y gana medidas estándar.
UPDATE SYSADM.BA_PRODUKTE_BEZ SET BA_BEZ1 = N'PRODUCTO DEMO 010 ACTUALIZADO' WHERE BA_PRODUKT = 10 AND SPRACH_ID = 0;
UPDATE SYSADM.BA_PRODUKTE SET BA_STD_HOEHE = 2500, BA_STD_BREITE = 1300, TRANSACTION_TIME = GETDATE() WHERE BA_PRODUKT = 10;
