SET NOCOUNT ON;
-- Cliente 150 y producto 160 desaparecen del origen (A+W no emite bajas lógicas por borrado).
DELETE FROM SYSADM.KU_KUNDEN WHERE ID = 150;
DELETE FROM SYSADM.BA_STUKL WHERE PRODUKT = 160;
DELETE FROM SYSADM.BA_PRODUKTE_BEZ WHERE BA_PRODUKT = 160;
DELETE FROM SYSADM.BA_PRODUKTE WHERE BA_PRODUKT = 160;
