SET NOCOUNT ON;
-- Segundo cliente con el mismo RFC (copia de ID 5) y otro ID.
DELETE FROM SYSADM.KU_KUNDEN WHERE ID = 1001;
INSERT SYSADM.KU_KUNDEN (ID, MANDANT, NAME1, NAME2, NAME3, STRASSE, ORT, PLZ, LAND, TLF1, TLF2, MAIL, WAEHRUNG, ZAHLBED, UST_ID, KZ_STATUS, KZ_GESPERRT, DATUM, PROVINZ, STEUERNUMMER)
SELECT 1001, MANDANT, N'CLIENTE DEMO 005 DUPLICADO', NAME2, NAME3, STRASSE, ORT, PLZ, LAND, TLF1, TLF2, MAIL, WAEHRUNG, ZAHLBED, UST_ID, KZ_STATUS, KZ_GESPERRT, DATUM, PROVINZ, STEUERNUMMER
FROM SYSADM.KU_KUNDEN WHERE ID = 5;
