// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Millet.CuentasPorCobrar.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Millet.CuentasPorCobrar.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CuentasPorCobrarDbContext))]
    [Migration("20260714014353_ClasificacionLineaCredito")]
    partial class ClasificacionLineaCredito
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cuentas_por_cobrar")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Millet.CuentasPorCobrar.Domain.Cartera.FacturaCartera", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<Guid>("FacturaVentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("factura_venta_id");

                    b.Property<DateTimeOffset>("FechaTimbrado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_timbrado");

                    b.Property<DateTimeOffset>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("folio");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("metodo_pago");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moneda");

                    b.Property<decimal>("MontoNc")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("monto_nc");

                    b.Property<decimal>("MontoPagado")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("monto_pagado");

                    b.Property<string>("ReceptorNombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("receptor_nombre");

                    b.Property<string>("ReceptorRfc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("receptor_rfc");

                    b.Property<decimal>("Total")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_factura_cartera");

                    b.HasIndex("FacturaVentaId")
                        .IsUnique()
                        .HasDatabaseName("ux_factura_cartera_factura_venta");

                    b.HasIndex("FechaVencimiento")
                        .HasDatabaseName("ix_factura_cartera_vencimiento_abiertas")
                        .HasFilter("estado IN (1, 2)");

                    b.HasIndex("ReceptorRfc")
                        .HasDatabaseName("ix_factura_cartera_receptor_rfc");

                    b.HasIndex("ClienteId", "Estado")
                        .HasDatabaseName("ix_factura_cartera_cliente_estado");

                    b.ToTable("factura_cartera", "cuentas_por_cobrar", t =>
                        {
                            t.HasCheckConstraint("ck_factura_cartera_acumulados", "monto_pagado >= 0 AND monto_nc >= 0 AND monto_pagado + monto_nc <= total");

                            t.HasCheckConstraint("ck_factura_cartera_estado", "estado IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("ck_factura_cartera_total_positivo", "total > 0");
                        });
                });

            modelBuilder.Entity("Millet.CuentasPorCobrar.Domain.Cartera.MovimientoCartera", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("FacturaCarteraId")
                        .HasColumnType("uuid")
                        .HasColumnName("factura_cartera_id");

                    b.Property<DateTimeOffset>("FechaMovimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_movimiento");

                    b.Property<decimal>("Importe")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("importe");

                    b.Property<Guid>("OrigenComprobanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("origen_comprobante_id");

                    b.Property<bool>("Revertido")
                        .HasColumnType("boolean")
                        .HasColumnName("revertido");

                    b.Property<DateTimeOffset?>("RevertidoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revertido_en");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_movimiento_cartera");

                    b.HasIndex("FacturaCarteraId")
                        .HasDatabaseName("ix_movimiento_cartera_factura");

                    b.HasIndex("OrigenComprobanteId")
                        .HasDatabaseName("ix_movimiento_cartera_origen");

                    b.ToTable("movimiento_cartera", "cuentas_por_cobrar", t =>
                        {
                            t.HasCheckConstraint("ck_movimiento_cartera_importe_positivo", "importe > 0");

                            t.HasCheckConstraint("ck_movimiento_cartera_reversa_consistente", "(revertido = TRUE AND revertido_en IS NOT NULL) OR (revertido = FALSE)");

                            t.HasCheckConstraint("ck_movimiento_cartera_tipo", "tipo IN (1, 2)");
                        });
                });

            modelBuilder.Entity("Millet.CuentasPorCobrar.Domain.Cobranza.SeguimientoCobranza", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Canal")
                        .HasColumnType("smallint")
                        .HasColumnName("canal");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<DateOnly?>("FechaComprometida")
                        .HasColumnType("date")
                        .HasColumnName("fecha_comprometida");

                    b.Property<decimal?>("MontoComprometido")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("monto_comprometido");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("nota");

                    b.Property<short>("Resultado")
                        .HasColumnType("smallint")
                        .HasColumnName("resultado");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_seguimiento_cobranza");

                    b.HasIndex("FechaComprometida")
                        .HasDatabaseName("ix_seguimiento_cobranza_promesas")
                        .HasFilter("resultado = 1");

                    b.HasIndex("ClienteId", "Fecha")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_seguimiento_cobranza_cliente_fecha");

                    b.ToTable("seguimiento_cobranza", "cuentas_por_cobrar", t =>
                        {
                            t.HasCheckConstraint("ck_seguimiento_cobranza_canal", "canal IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_seguimiento_cobranza_promesa_consistente", "(resultado = 1 AND monto_comprometido IS NOT NULL AND monto_comprometido > 0 AND fecha_comprometida IS NOT NULL) OR (resultado != 1 AND monto_comprometido IS NULL AND fecha_comprometida IS NULL)");

                            t.HasCheckConstraint("ck_seguimiento_cobranza_resultado", "resultado IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("Millet.CuentasPorCobrar.Domain.Eventos.EventoProcesado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Detalle")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detalle");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<string>("EventoTipo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("evento_tipo");

                    b.Property<DateTimeOffset>("ProcesadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("procesado_en");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_eventos_procesados");

                    b.HasIndex("EventoId", "EventoTipo")
                        .IsUnique()
                        .HasDatabaseName("ux_eventos_procesados_id_tipo");

                    b.ToTable("eventos_procesados", "cuentas_por_cobrar");
                });

            modelBuilder.Entity("Millet.CuentasPorCobrar.Domain.Liberacion.AutorizacionCredito", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BeneficiarioUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("beneficiario_usuario_id");

                    b.Property<string>("ClienteOPedidoRef")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("cliente_o_pedido_ref");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("DecisionLiberacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_liberacion_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaAutorizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_autorizacion");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("motivo");

                    b.Property<Guid>("SupervisorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("supervisor_usuario_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset>("VigenteHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigente_hasta");

                    b.HasKey("Id")
                        .HasName("pk_autorizacion_credito");

                    b.HasIndex("BeneficiarioUsuarioId", "Estado")
                        .HasDatabaseName("ix_autorizacion_credito_beneficiario_estado");

                    b.ToTable("autorizacion_credito", "cuentas_por_cobrar", t =>
                        {
                            t.HasCheckConstraint("ck_autorizacion_credito_estado", "estado IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_autorizacion_credito_no_autoconsumo", "supervisor_usuario_id != beneficiario_usuario_id");

                            t.HasCheckConstraint("ck_autorizacion_credito_uso_consistente", "(estado = 2 AND decision_liberacion_id IS NOT NULL) OR (estado != 2 AND decision_liberacion_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Millet.CuentasPorCobrar.Domain.Liberacion.DecisionLiberacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<decimal>("CreditoDisponibleSnapshot")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("credito_disponible_snapshot");

                    b.Property<DateTimeOffset>("DecididoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decidido_en");

                    b.Property<Guid>("DecididoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("decidido_por");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moneda");

                    b.Property<decimal>("MontoPedido")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("monto_pedido");

                    b.Property<Guid?>("OverrideId")
                        .HasColumnType("uuid")
                        .HasColumnName("override_id");

                    b.Property<string>("PedidoRef")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("pedido_ref");

                    b.Property<short>("ReglaAplicada")
                        .HasColumnType("smallint")
                        .HasColumnName("regla_aplicada");

                    b.Property<short>("Resultado")
                        .HasColumnType("smallint")
                        .HasColumnName("resultado");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_decision_liberacion");

                    b.HasIndex("PedidoRef")
                        .HasDatabaseName("ix_decision_liberacion_pedido");

                    b.HasIndex("ClienteId", "DecididoEn")
                        .HasDatabaseName("ix_decision_liberacion_cliente_fecha");

                    b.ToTable("decision_liberacion", "cuentas_por_cobrar", t =>
                        {
                            t.HasCheckConstraint("ck_decision_liberacion_monto_positivo", "monto_pedido > 0");

                            t.HasCheckConstraint("ck_decision_liberacion_override_consistente", "(resultado = 3 AND override_id IS NOT NULL) OR (resultado != 3 AND override_id IS NULL)");

                            t.HasCheckConstraint("ck_decision_liberacion_regla", "regla_aplicada IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_decision_liberacion_resultado", "resultado IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Millet.CuentasPorCobrar.Domain.Liberacion.ReglaLiberacionSerie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<short>("Comportamiento")
                        .HasColumnType("smallint")
                        .HasColumnName("comportamiento");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("prefijo");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_regla_liberacion_serie");

                    b.HasIndex("Prefijo")
                        .IsUnique()
                        .HasDatabaseName("ux_regla_liberacion_prefijo");

                    b.ToTable("regla_liberacion_serie", "cuentas_por_cobrar", t =>
                        {
                            t.HasCheckConstraint("ck_regla_liberacion_comportamiento", "comportamiento IN (1, 2, 3)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0000000a-1001-0000-0000-000000000001"),
                            Activo = true,
                            Comportamiento = (short)1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Prefijo = "5000",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("0000000a-1001-0000-0000-000000000002"),
                            Activo = true,
                            Comportamiento = (short)1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Prefijo = "7000",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("0000000a-1001-0000-0000-000000000003"),
                            Activo = true,
                            Comportamiento = (short)2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Prefijo = "3000",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("0000000a-1001-0000-0000-000000000004"),
                            Activo = true,
                            Comportamiento = (short)2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Prefijo = "4000",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("0000000a-1001-0000-0000-000000000005"),
                            Activo = true,
                            Comportamiento = (short)2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Prefijo = "8000",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        });
                });

            modelBuilder.Entity("Millet.CuentasPorCobrar.Domain.LineaCredito.LineaCredito", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Clasificacion")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("clasificacion");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<decimal>("Limite")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("limite");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moneda");

                    b.Property<string>("MotivoBloqueo")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("motivo_bloqueo");

                    b.Property<short>("Origen")
                        .HasColumnType("smallint")
                        .HasColumnName("origen");

                    b.Property<int>("PlazoDias")
                        .HasColumnType("integer")
                        .HasColumnName("plazo_dias");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_linea_credito");

                    b.HasIndex("ClienteId", "Estado")
                        .HasDatabaseName("ix_linea_credito_cliente_estado");

                    b.HasIndex("ClienteId", "Moneda")
                        .IsUnique()
                        .HasDatabaseName("ux_linea_credito_cliente_moneda_activa")
                        .HasFilter("estado = 1");

                    b.ToTable("linea_credito", "cuentas_por_cobrar", t =>
                        {
                            t.HasCheckConstraint("ck_linea_credito_bloqueo_consistente", "(estado = 2 AND motivo_bloqueo IS NOT NULL) OR (estado != 2)");

                            t.HasCheckConstraint("ck_linea_credito_clasificacion", "clasificacion IS NULL OR clasificacion IN ('A', 'B', 'C', 'E')");

                            t.HasCheckConstraint("ck_linea_credito_estado", "estado IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_linea_credito_limite_positivo", "limite > 0");

                            t.HasCheckConstraint("ck_linea_credito_moneda", "moneda IN ('MXN', 'USD')");

                            t.HasCheckConstraint("ck_linea_credito_origen", "origen IN (1, 2)");

                            t.HasCheckConstraint("ck_linea_credito_plazo_positivo", "plazo_dias > 0");
                        });
                });

            modelBuilder.Entity("Millet.SharedKernel.Domain.Audit.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("AggregateRootId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_root_id");

                    b.Property<string>("Cambios")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cambios");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entidad");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<bool>("EsBulk")
                        .HasColumnType("boolean")
                        .HasColumnName("es_bulk");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<string>("Metadatos")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadatos");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("modulo");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operacion");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id", "Timestamp")
                        .HasName("pk_audit_log");

                    b.HasIndex("EmpresaId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_empresa_id_timestamp");

                    b.HasIndex("UsuarioId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_usuario_id_timestamp");

                    b.HasIndex("Modulo", "AggregateRootId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_modulo_aggregate_root_id_timestamp");

                    b.HasIndex("Modulo", "Entidad", "EntidadId")
                        .HasDatabaseName("ix_audit_log_modulo_entidad_entidad_id");

                    b.ToTable("audit_log", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Millet.SharedKernel.Infrastructure.Outbox.IntegrationEventOutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("IntegrationEmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_empresa_id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_integration_events_outbox");

                    b.HasIndex("IntegrationEmpresaId")
                        .HasDatabaseName("ix_integration_events_outbox_integration_empresa_id");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_integration_events_outbox_pending")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("integration_events_outbox", "cuentas_por_cobrar");
                });

            modelBuilder.Entity("Millet.CuentasPorCobrar.Domain.Cartera.MovimientoCartera", b =>
                {
                    b.HasOne("Millet.CuentasPorCobrar.Domain.Cartera.FacturaCartera", null)
                        .WithMany()
                        .HasForeignKey("FacturaCarteraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimiento_cartera_factura_cartera_factura_cartera_id");
                });
#pragma warning restore 612, 618
        }
    }
}
