// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Millet.Identidad.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Millet.Identidad.Infrastructure.Migrations
{
    [DbContext(typeof(IdentidadDbContext))]
    [Migration("20260503140718_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identidad")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Millet.SharedKernel.Domain.Audit.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cambios")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cambios");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entidad");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<bool>("EsBulk")
                        .HasColumnType("boolean")
                        .HasColumnName("es_bulk");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<string>("Metadatos")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadatos");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("modulo");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operacion");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("EmpresaId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_empresa_id_timestamp");

                    b.HasIndex("UsuarioId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_usuario_id_timestamp");

                    b.HasIndex("Modulo", "Entidad", "EntidadId")
                        .HasDatabaseName("ix_audit_log_modulo_entidad_entidad_id");

                    b.ToTable("audit_log", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
