// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Millet.Integraciones.Aw.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Millet.Integraciones.Aw.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IntegracionesAwDbContext))]
    [Migration("20260630030228_AgregarPdfDocumentoAEntidadExterna")]
    partial class AgregarPdfDocumentoAEntidadExterna
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("integraciones_aw")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Millet.Integraciones.Aw.Domain.Correlacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AwDocId")
                        .HasColumnType("bigint")
                        .HasColumnName("aw_doc_id");

                    b.Property<string>("AwDocIdSecondary")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("aw_doc_id_secondary");

                    b.Property<string>("AwRecordSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("aw_record_snapshot");

                    b.Property<DateTimeOffset>("CorrelatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("correlated_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EntidadExternaId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_externa_id");

                    b.Property<int>("PollingCycleNumber")
                        .HasColumnType("integer")
                        .HasColumnName("polling_cycle_number");

                    b.Property<int?>("PollingQueryDurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("polling_query_duration_ms");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_correlacion");

                    b.HasIndex("EntidadExternaId")
                        .IsUnique()
                        .HasDatabaseName("uq_correlacion_entidad_externa");

                    b.ToTable("correlacion", "integraciones_aw");
                });

            modelBuilder.Entity("Millet.Integraciones.Aw.Domain.EntidadExterna", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AwDiagnosticLog")
                        .HasColumnType("text")
                        .HasColumnName("aw_diagnostic_log");

                    b.Property<long?>("AwDocId")
                        .HasColumnType("bigint")
                        .HasColumnName("aw_doc_id");

                    b.Property<string>("AwDocIdSecondary")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("aw_doc_id_secondary");

                    b.Property<string>("AwErrorCodes")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("aw_error_codes");

                    b.Property<string>("AwErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("aw_error_message");

                    b.Property<DateTimeOffset?>("CorrelatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("correlated_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("DeliveredToAwAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_to_aw_at");

                    b.Property<string>("EdiContent")
                        .HasColumnType("text")
                        .HasColumnName("edi_content");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<Guid?>("PayloadBlobId")
                        .HasColumnType("uuid")
                        .HasColumnName("payload_blob_id");

                    b.Property<string>("PayloadOriginal")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_original");

                    b.Property<string>("PdfBlobUrl")
                        .HasColumnType("text")
                        .HasColumnName("pdf_blob_url");

                    b.Property<string>("PdfFilename")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("pdf_filename");

                    b.Property<DateTimeOffset?>("PdfUploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pdf_uploaded_at");

                    b.Property<string>("ReferenciaExterna")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("referencia_externa");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text")
                        .HasColumnName("resolution_note");

                    b.Property<short>("RetryCount")
                        .HasColumnType("smallint")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid?>("SubmittedBySpnId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_spn_id");

                    b.Property<string>("Sucursal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sucursal");

                    b.Property<short>("TipoEntidad")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_entidad");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_entidad_externa");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_entidad_externa_empresa_id");

                    b.HasIndex("Estado", "SubmittedAt")
                        .HasDatabaseName("ix_entidad_externa_pendientes")
                        .HasFilter("estado IN (0, 3, 4)");

                    b.HasIndex("TipoEntidad", "AwDocId")
                        .HasDatabaseName("ix_entidad_externa_aw_doc")
                        .HasFilter("aw_doc_id IS NOT NULL");

                    b.HasIndex("TipoEntidad", "ReferenciaExterna", "EmpresaId")
                        .IsUnique()
                        .HasDatabaseName("uq_entidad_externa_tipo_referencia_empresa");

                    b.HasIndex(new[] { "TipoEntidad", "AwDocId" }, "ix_entidad_externa_pdf_pendiente")
                        .HasDatabaseName("ix_entidad_externa_pdf_pendiente")
                        .HasFilter("estado = 2 AND aw_doc_id IS NOT NULL AND pdf_blob_url IS NULL");

                    b.ToTable("entidad_externa", "integraciones_aw");
                });

            modelBuilder.Entity("Millet.Integraciones.Aw.Domain.Envio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("AttemptNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("attempt_number");

                    b.Property<int?>("BytesSent")
                        .HasColumnType("integer")
                        .HasColumnName("bytes_sent");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DropServiceUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("drop_service_url");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<Guid>("EntidadExternaId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_externa_id");

                    b.Property<string>("ErrorKind")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("error_kind");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Filename")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("filename");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<short?>("HttpStatusCode")
                        .HasColumnType("smallint")
                        .HasColumnName("http_status_code");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_envio");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_envio_failed_recent")
                        .HasFilter("status = 2");

                    b.HasIndex("EntidadExternaId", "AttemptNumber")
                        .HasDatabaseName("ix_envio_entidad_attempt");

                    b.ToTable("envio", "integraciones_aw");
                });

            modelBuilder.Entity("Millet.SharedKernel.Domain.Audit.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("AggregateRootId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_root_id");

                    b.Property<string>("Cambios")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cambios");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entidad");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<bool>("EsBulk")
                        .HasColumnType("boolean")
                        .HasColumnName("es_bulk");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<string>("Metadatos")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadatos");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("modulo");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operacion");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id", "Timestamp")
                        .HasName("pk_audit_log");

                    b.HasIndex("EmpresaId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_empresa_id_timestamp");

                    b.HasIndex("UsuarioId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_usuario_id_timestamp");

                    b.HasIndex("Modulo", "AggregateRootId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_modulo_aggregate_root_id_timestamp");

                    b.HasIndex("Modulo", "Entidad", "EntidadId")
                        .HasDatabaseName("ix_audit_log_modulo_entidad_entidad_id");

                    b.ToTable("audit_log", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Millet.SharedKernel.Infrastructure.Outbox.IntegrationEventOutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("IntegrationEmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_empresa_id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_integration_events_outbox");

                    b.HasIndex("IntegrationEmpresaId")
                        .HasDatabaseName("ix_integration_events_outbox_integration_empresa_id");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_integration_events_outbox_pending")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("integration_events_outbox", "integraciones_aw");
                });

            modelBuilder.Entity("Millet.Integraciones.Aw.Domain.Correlacion", b =>
                {
                    b.HasOne("Millet.Integraciones.Aw.Domain.EntidadExterna", null)
                        .WithMany()
                        .HasForeignKey("EntidadExternaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_correlacion_entidad_externa_entidad_externa_id");
                });

            modelBuilder.Entity("Millet.Integraciones.Aw.Domain.Envio", b =>
                {
                    b.HasOne("Millet.Integraciones.Aw.Domain.EntidadExterna", null)
                        .WithMany()
                        .HasForeignKey("EntidadExternaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_envio_entidad_externa_entidad_externa_id");
                });
#pragma warning restore 612, 618
        }
    }
}
