USE AW_FULL;
SET NOCOUNT ON;
DECLARE @id int=(SELECT TOP 1 ID FROM SYSADM.KU_KUNDEN WHERE TRANSACTION_TIME IS NULL ORDER BY ID DESC);
DECLARE @orig int=(SELECT KZ_GESPERRT FROM SYSADM.KU_KUNDEN WHERE ID=@id);
DECLARE @p int=(SELECT TOP 1 BA_PRODUKT FROM SYSADM.BA_PRODUKTE WHERE BA_PRODUKT<>0 ORDER BY BA_PRODUKT DESC);
DECLARE @po int=(SELECT KZ_GESPERRT FROM SYSADM.BA_PRODUKTE WHERE BA_PRODUKT=@p);
-- 1) UPDATE cliente y producto (sin tocar TRANSACTION_TIME: CDC no depende de él)
UPDATE SYSADM.KU_KUNDEN SET KZ_GESPERRT=(@orig+1)%3 WHERE ID=@id;
UPDATE SYSADM.BA_PRODUKTE SET KZ_GESPERRT=(@po+1)%3 WHERE BA_PRODUKT=@p;
-- 2) DELETE + reinserción de una línea de BOM (borrado físico)
SELECT * INTO #bom FROM SYSADM.BA_STUKL WHERE PRODUKT=(SELECT TOP 1 PRODUKT FROM SYSADM.BA_STUKL ORDER BY PRODUKT DESC) AND BOM_POS=(SELECT TOP 1 BOM_POS FROM SYSADM.BA_STUKL ORDER BY PRODUKT DESC,BOM_POS);
DELETE s FROM SYSADM.BA_STUKL s JOIN #bom b ON b.PRODUKT=s.PRODUKT AND b.BOM_ID=s.BOM_ID AND b.BOM_POS=s.BOM_POS;
PRINT 'filas BOM borradas: '+CAST(@@ROWCOUNT AS varchar);
-- restaurar
UPDATE SYSADM.KU_KUNDEN SET KZ_GESPERRT=@orig WHERE ID=@id;
UPDATE SYSADM.BA_PRODUKTE SET KZ_GESPERRT=@po WHERE BA_PRODUKT=@p;
INSERT SYSADM.BA_STUKL SELECT * FROM #bom;
WAITFOR DELAY '00:00:07';  -- el job de captura sondea cada ~5 s
DECLARE @from binary(10)=sys.fn_cdc_get_min_lsn('SYSADM_KU_KUNDEN'), @to binary(10)=sys.fn_cdc_get_max_lsn();
SELECT 'KU_KUNDEN' t, CASE __$operation WHEN 1 THEN 'DELETE' WHEN 2 THEN 'INSERT' WHEN 3 THEN 'UPD-antes' WHEN 4 THEN 'UPD-despues' END op, ID, KZ_GESPERRT FROM cdc.fn_cdc_get_all_changes_SYSADM_KU_KUNDEN(@from,@to,'all update old');
SET @from=sys.fn_cdc_get_min_lsn('SYSADM_BA_PRODUKTE');
SELECT 'BA_PRODUKTE' t, CASE __$operation WHEN 1 THEN 'DELETE' WHEN 2 THEN 'INSERT' WHEN 3 THEN 'UPD-antes' WHEN 4 THEN 'UPD-despues' END op, BA_PRODUKT, KZ_GESPERRT FROM cdc.fn_cdc_get_all_changes_SYSADM_BA_PRODUKTE(@from,@to,'all update old');
SET @from=sys.fn_cdc_get_min_lsn('SYSADM_BA_STUKL');
SELECT 'BA_STUKL' t, CASE __$operation WHEN 1 THEN 'DELETE' WHEN 2 THEN 'INSERT' END op, PRODUKT, BOM_ID, BOM_POS FROM cdc.fn_cdc_get_all_changes_SYSADM_BA_STUKL(@from,@to,'all');
