// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Millet.Compartido.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Millet.Compartido.Infrastructure.Migrations.Compartido
{
    [DbContext(typeof(CompartidoDbContext))]
    [Migration("20260512034020_UsosPrincipalesSeed")]
    partial class UsosPrincipalesSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("compartido")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Millet.Almacen.Domain.Almacen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clave");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<short>("Estatus")
                        .HasColumnType("smallint")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_almacenes");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("ix_almacenes_clave");

                    b.HasIndex("Estatus")
                        .HasDatabaseName("ix_almacenes_estatus");

                    b.HasIndex("SucursalId")
                        .HasDatabaseName("ix_almacenes_sucursal_id");

                    b.ToTable("almacenes", "compartido", t =>
                        {
                            t.HasCheckConstraint("ck_almacenes_estatus", "estatus BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Millet.DatosMaestros.Domain.Articulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clave");

                    b.Property<string>("ClaveLegacy")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clave_legacy");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DescripcionLarga")
                        .HasColumnType("text")
                        .HasColumnName("descripcion_larga");

                    b.Property<short>("Estatus")
                        .HasColumnType("smallint")
                        .HasColumnName("estatus");

                    b.Property<short>("Naturaleza")
                        .HasColumnType("smallint")
                        .HasColumnName("naturaleza");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("nombre");

                    b.Property<string>("PrecioReferenciaMoneda")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("precio_referencia_moneda");

                    b.Property<decimal?>("PrecioReferenciaMonto")
                        .HasPrecision(15, 4)
                        .HasColumnType("numeric(15,4)")
                        .HasColumnName("precio_referencia_monto");

                    b.Property<string>("UnidadMedidaDefault")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidad_medida_default");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_articulos");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("ix_articulos_clave");

                    b.HasIndex("Estatus")
                        .HasDatabaseName("ix_articulos_estatus");

                    b.HasIndex("Naturaleza")
                        .HasDatabaseName("ix_articulos_naturaleza");

                    b.ToTable("articulos", "compartido", t =>
                        {
                            t.HasCheckConstraint("ck_articulos_estatus", "estatus BETWEEN 0 AND 2");

                            t.HasCheckConstraint("ck_articulos_naturaleza", "naturaleza BETWEEN 0 AND 3");

                            t.HasCheckConstraint("ck_articulos_precio_moneda_iso", "precio_referencia_moneda IS NULL OR precio_referencia_moneda ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_articulos_precio_no_negativo", "precio_referencia_monto IS NULL OR precio_referencia_monto >= 0");
                        });
                });

            modelBuilder.Entity("Millet.SharedKernel.Domain.Audit.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("AggregateRootId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_root_id");

                    b.Property<string>("Cambios")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cambios");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entidad");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<bool>("EsBulk")
                        .HasColumnType("boolean")
                        .HasColumnName("es_bulk");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<string>("Metadatos")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadatos");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("modulo");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operacion");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id", "Timestamp")
                        .HasName("pk_audit_log");

                    b.HasIndex("EmpresaId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_empresa_id_timestamp");

                    b.HasIndex("UsuarioId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_usuario_id_timestamp");

                    b.HasIndex("Modulo", "AggregateRootId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_modulo_aggregate_root_id_timestamp");

                    b.HasIndex("Modulo", "Entidad", "EntidadId")
                        .HasDatabaseName("ix_audit_log_modulo_entidad_entidad_id");

                    b.ToTable("audit_log", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Millet.Catalogos.Domain.CondicionesPago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clave");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DiasCredito")
                        .HasColumnType("integer")
                        .HasColumnName("dias_credito");

                    b.Property<short>("Estatus")
                        .HasColumnType("smallint")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_condiciones_pago");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("ix_condiciones_pago_clave");

                    b.HasIndex("Estatus")
                        .HasDatabaseName("ix_condiciones_pago_estatus");

                    b.ToTable("condiciones_pago", "compartido", t =>
                        {
                            t.HasCheckConstraint("ck_condiciones_pago_dias", "dias_credito BETWEEN 0 AND 365");

                            t.HasCheckConstraint("ck_condiciones_pago_estatus", "estatus BETWEEN 0 AND 2");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000002-0003-0000-0000-000000000001"),
                            Clave = "CONTADO",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            DiasCredito = 0,
                            Estatus = (short)0,
                            Nombre = "Contado",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0003-0000-0000-000000000002"),
                            Clave = "15D",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            DiasCredito = 15,
                            Estatus = (short)0,
                            Nombre = "15 días",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0003-0000-0000-000000000003"),
                            Clave = "30D",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            DiasCredito = 30,
                            Estatus = (short)0,
                            Nombre = "30 días",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0003-0000-0000-000000000004"),
                            Clave = "45D",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            DiasCredito = 45,
                            Estatus = (short)0,
                            Nombre = "45 días",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0003-0000-0000-000000000005"),
                            Clave = "60D",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            DiasCredito = 60,
                            Estatus = (short)0,
                            Nombre = "60 días",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0003-0000-0000-000000000006"),
                            Clave = "90D",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            DiasCredito = 90,
                            Estatus = (short)0,
                            Nombre = "90 días",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0003-0000-0000-000000000007"),
                            Clave = "120D",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            DiasCredito = 120,
                            Estatus = (short)0,
                            Nombre = "120 días",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        });
                });

            modelBuilder.Entity("Millet.Administracion.Domain.Departamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clave");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<short>("Estatus")
                        .HasColumnType("smallint")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_departamentos");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("ix_departamentos_clave");

                    b.HasIndex("Estatus")
                        .HasDatabaseName("ix_departamentos_estatus");

                    b.ToTable("departamentos", "compartido", t =>
                        {
                            t.HasCheckConstraint("ck_departamentos_estatus", "estatus BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Millet.Administracion.Domain.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("nombre_comercial");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("razon_social");

                    b.Property<string>("RegimenFiscal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("regimen_fiscal");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("rfc");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_empresas");

                    b.HasIndex("Rfc")
                        .IsUnique()
                        .HasDatabaseName("ix_empresas_rfc");

                    b.ToTable("empresas", "compartido");
                });

            modelBuilder.Entity("Millet.Catalogos.Domain.Incoterm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<short>("Estatus")
                        .HasColumnType("smallint")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_incoterms");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_incoterms_codigo");

                    b.HasIndex("Estatus")
                        .HasDatabaseName("ix_incoterms_estatus");

                    b.ToTable("incoterms", "compartido", t =>
                        {
                            t.HasCheckConstraint("ck_incoterms_estatus", "estatus BETWEEN 0 AND 2");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000002-0001-0000-0000-000000000001"),
                            Codigo = "EXW",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Ex Works",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0001-0000-0000-000000000002"),
                            Codigo = "FCA",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Free Carrier",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0001-0000-0000-000000000003"),
                            Codigo = "CPT",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Carriage Paid To",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0001-0000-0000-000000000004"),
                            Codigo = "CIP",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Carriage and Insurance Paid To",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0001-0000-0000-000000000005"),
                            Codigo = "DAP",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Delivered at Place",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0001-0000-0000-000000000006"),
                            Codigo = "DPU",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Delivered at Place Unloaded",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0001-0000-0000-000000000007"),
                            Codigo = "DDP",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Delivered Duty Paid",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0001-0000-0000-000000000008"),
                            Codigo = "FAS",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Free Alongside Ship",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0001-0000-0000-000000000009"),
                            Codigo = "FOB",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Free on Board",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0001-0000-0000-000000000010"),
                            Codigo = "CFR",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Cost and Freight",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0001-0000-0000-000000000011"),
                            Codigo = "CIF",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Cost, Insurance and Freight",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        });
                });

            modelBuilder.Entity("Millet.Catalogos.Domain.Moneda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("Decimales")
                        .HasColumnType("integer")
                        .HasColumnName("decimales");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_monedas");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_monedas_codigo");

                    b.ToTable("monedas", "compartido");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000001"),
                            Activa = true,
                            Codigo = "MXN",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Decimales = 2,
                            Nombre = "Peso Mexicano",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000002"),
                            Activa = true,
                            Codigo = "USD",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Decimales = 2,
                            Nombre = "Dólar EUA",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000003"),
                            Activa = true,
                            Codigo = "EUR",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Decimales = 2,
                            Nombre = "Euro",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000004"),
                            Activa = true,
                            Codigo = "CAD",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Decimales = 2,
                            Nombre = "Dólar Canadiense",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000005"),
                            Activa = true,
                            Codigo = "GBP",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Decimales = 2,
                            Nombre = "Libra Esterlina",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000006"),
                            Activa = true,
                            Codigo = "JPY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Decimales = 0,
                            Nombre = "Yen Japonés",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000007"),
                            Activa = true,
                            Codigo = "CHF",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Decimales = 2,
                            Nombre = "Franco Suizo",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000008"),
                            Activa = true,
                            Codigo = "CNY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Decimales = 2,
                            Nombre = "Yuan Chino",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000009"),
                            Activa = true,
                            Codigo = "BRL",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Decimales = 2,
                            Nombre = "Real Brasileño",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000010"),
                            Activa = true,
                            Codigo = "ARS",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Decimales = 2,
                            Nombre = "Peso Argentino",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000011"),
                            Activa = true,
                            Codigo = "COP",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Decimales = 2,
                            Nombre = "Peso Colombiano",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000012"),
                            Activa = true,
                            Codigo = "CLP",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Decimales = 0,
                            Nombre = "Peso Chileno",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        });
                });

            modelBuilder.Entity("Millet.DatosMaestros.Domain.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clave");

                    b.Property<string>("ClaveLegacy")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clave_legacy");

                    b.Property<short?>("CondicionesPagoDias")
                        .HasColumnType("smallint")
                        .HasColumnName("condiciones_pago_dias");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<short>("Estatus")
                        .HasColumnType("smallint")
                        .HasColumnName("estatus");

                    b.Property<Guid?>("MonedaPreferidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("moneda_preferida_id");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("nombre_comercial");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("rfc");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.Property<short>("TipoPersona")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_persona");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_proveedores");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("ix_proveedores_clave");

                    b.HasIndex("Estatus")
                        .HasDatabaseName("ix_proveedores_estatus");

                    b.HasIndex("Rfc")
                        .HasDatabaseName("ix_proveedores_rfc");

                    b.ToTable("proveedores", "compartido", t =>
                        {
                            t.HasCheckConstraint("ck_proveedores_condiciones_pago", "condiciones_pago_dias IS NULL OR condiciones_pago_dias BETWEEN 0 AND 365");

                            t.HasCheckConstraint("ck_proveedores_estatus", "estatus BETWEEN 0 AND 2");

                            t.HasCheckConstraint("ck_proveedores_rfc_longitud", "char_length(rfc) BETWEEN 12 AND 13");

                            t.HasCheckConstraint("ck_proveedores_tipo_persona", "tipo_persona BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("Millet.Catalogos.Domain.RegimenFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AplicaPersonaFisica")
                        .HasColumnType("boolean")
                        .HasColumnName("aplica_persona_fisica");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<short>("Estatus")
                        .HasColumnType("smallint")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_regimenes_fiscales");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_regimenes_fiscales_codigo");

                    b.HasIndex("Estatus")
                        .HasDatabaseName("ix_regimenes_fiscales_estatus");

                    b.ToTable("regimenes_fiscales", "compartido", t =>
                        {
                            t.HasCheckConstraint("ck_regimenes_fiscales_codigo_3", "char_length(codigo) = 3");

                            t.HasCheckConstraint("ck_regimenes_fiscales_estatus", "estatus BETWEEN 0 AND 2");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000002-0002-0000-0000-000000000001"),
                            AplicaPersonaFisica = false,
                            Codigo = "601",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "General de Ley Personas Morales",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0002-0000-0000-000000000002"),
                            AplicaPersonaFisica = false,
                            Codigo = "603",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Personas Morales con Fines no Lucrativos",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0002-0000-0000-000000000003"),
                            AplicaPersonaFisica = true,
                            Codigo = "605",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Sueldos y Salarios e Ingresos Asimilados a Salarios",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0002-0000-0000-000000000004"),
                            AplicaPersonaFisica = true,
                            Codigo = "606",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Arrendamiento",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0002-0000-0000-000000000005"),
                            AplicaPersonaFisica = true,
                            Codigo = "612",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Personas Físicas con Actividades Empresariales y Profesionales",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0002-0000-0000-000000000006"),
                            AplicaPersonaFisica = true,
                            Codigo = "621",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Incorporación Fiscal",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0002-0000-0000-000000000007"),
                            AplicaPersonaFisica = true,
                            Codigo = "625",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0002-0000-0000-000000000008"),
                            AplicaPersonaFisica = true,
                            Codigo = "626",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Régimen Simplificado de Confianza (RESICO)",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        });
                });

            modelBuilder.Entity("Millet.Administracion.Domain.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clave");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<short>("Estatus")
                        .HasColumnType("smallint")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_sucursales");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("ix_sucursales_clave");

                    b.HasIndex("Estatus")
                        .HasDatabaseName("ix_sucursales_estatus");

                    b.ToTable("sucursales", "compartido", t =>
                        {
                            t.HasCheckConstraint("ck_sucursales_estatus", "estatus BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Millet.Catalogos.Domain.Transportista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clave");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<short>("Estatus")
                        .HasColumnType("smallint")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_transportistas");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("ix_transportistas_clave");

                    b.HasIndex("Estatus")
                        .HasDatabaseName("ix_transportistas_estatus");

                    b.ToTable("transportistas", "compartido", t =>
                        {
                            t.HasCheckConstraint("ck_transportistas_estatus", "estatus BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Millet.Catalogos.Domain.UsoPrincipal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clave");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<short>("Estatus")
                        .HasColumnType("smallint")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_usos_principales");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("ix_usos_principales_clave");

                    b.HasIndex("Estatus")
                        .HasDatabaseName("ix_usos_principales_estatus");

                    b.ToTable("usos_principales", "compartido", t =>
                        {
                            t.HasCheckConstraint("ck_usos_principales_estatus", "estatus BETWEEN 0 AND 2");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000002-0004-0000-0000-000000000001"),
                            Clave = "MTTO_GEN",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Mantenimiento general",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0004-0000-0000-000000000002"),
                            Clave = "PRODUCCION",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Insumos de producción",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0004-0000-0000-000000000003"),
                            Clave = "SVC_PROF",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Servicios profesionales",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0004-0000-0000-000000000004"),
                            Clave = "INSUMO_OF",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Insumos de oficina",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0004-0000-0000-000000000005"),
                            Clave = "ACTIVO_FIJO",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Activo fijo",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0004-0000-0000-000000000006"),
                            Clave = "IMPORTACION",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Importación",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0004-0000-0000-000000000007"),
                            Clave = "REPARACION",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Reparaciones",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000002-0004-0000-0000-000000000008"),
                            Clave = "OTRO",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Estatus = (short)0,
                            Nombre = "Otro",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "seed",
                            Version = 1
                        });
                });

            modelBuilder.Entity("Millet.Almacen.Domain.Almacen", b =>
                {
                    b.HasOne("Millet.Administracion.Domain.Sucursal", null)
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_almacenes_sucursales_sucursal_id");
                });
#pragma warning restore 612, 618
        }
    }
}
