// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Millet.Contabilidad.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Millet.Contabilidad.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContabilidadDbContext))]
    partial class ContabilidadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("contabilidad")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Millet.Contabilidad.Domain.CuentaContable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Clase")
                        .HasColumnType("smallint")
                        .HasColumnName("clase");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoAgrupador")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo_agrupador");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<short>("CuentaControl")
                        .HasColumnType("smallint")
                        .HasColumnName("cuenta_control");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<short>("Estatus")
                        .HasColumnType("smallint")
                        .HasColumnName("estatus");

                    b.Property<string>("GrupoReporte")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("grupo_reporte");

                    b.Property<short?>("Naturaleza")
                        .HasColumnType("smallint")
                        .HasColumnName("naturaleza");

                    b.Property<short>("Nivel")
                        .HasColumnType("smallint")
                        .HasColumnName("nivel");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("nombre");

                    b.Property<Guid?>("PadreId")
                        .HasColumnType("uuid")
                        .HasColumnName("padre_id");

                    b.Property<Guid?>("RubroId")
                        .HasColumnType("uuid")
                        .HasColumnName("rubro_id");

                    b.Property<short?>("Tipo")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_cuentas_contables");

                    b.HasIndex("PadreId")
                        .HasDatabaseName("ix_cuentas_contables_padre_id");

                    b.HasIndex("RubroId")
                        .HasDatabaseName("ix_cuentas_contables_rubro_id");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_cuentas_contables_codigo");

                    b.HasIndex("EmpresaId", "PadreId")
                        .HasDatabaseName("ix_cuentas_contables_empresa_id_padre_id");

                    b.HasIndex("EmpresaId", "Estatus", "Tipo")
                        .HasDatabaseName("ix_cuentas_contables_empresa_id_estatus_tipo");

                    b.ToTable("cuentas_contables", "contabilidad", t =>
                        {
                            t.HasCheckConstraint("ck_cuentas_control_afectable", "cuenta_control = 0 OR COALESCE(tipo, -1) = 1");

                            t.HasCheckConstraint("ck_cuentas_estatus", "estatus BETWEEN 0 AND 2");

                            t.HasCheckConstraint("ck_cuentas_nivel", "nivel >= 1");

                            t.HasCheckConstraint("ck_cuentas_rubro", "(clase = 0 AND (rubro_id IS NULL OR padre_id IS NULL)) OR (clase = 1 AND padre_id IS NULL AND rubro_id IS NULL AND cuenta_control = 0)");
                        });
                });

            modelBuilder.Entity("Millet.Contabilidad.Domain.CuentaContableOrigen", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoOrigen")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("codigo_origen");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("fuente");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("lote_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_cuentas_contables_origen");

                    b.HasIndex("CuentaId")
                        .HasDatabaseName("ix_cuentas_contables_origen_cuenta_id");

                    b.HasIndex("LoteId")
                        .HasDatabaseName("ix_cuentas_contables_origen_lote_id");

                    b.HasIndex("EmpresaId", "Fuente", "CodigoOrigen")
                        .IsUnique()
                        .HasDatabaseName("ux_cuentas_origen_fuente_codigo");

                    b.ToTable("cuentas_contables_origen", "contabilidad");
                });

            modelBuilder.Entity("Millet.Contabilidad.Domain.CuentaContableUso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Consumidor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("consumidor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTimeOffset>("PrimerUsoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("primer_uso_en");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("referencia");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_cuentas_contables_uso");

                    b.HasIndex("CuentaId")
                        .HasDatabaseName("ix_cuentas_contables_uso_cuenta_id");

                    b.HasIndex("EmpresaId", "CuentaId")
                        .HasDatabaseName("ix_cuentas_contables_uso_empresa_id_cuenta_id");

                    b.ToTable("cuentas_contables_uso", "contabilidad");
                });

            modelBuilder.Entity("Millet.Contabilidad.Domain.ImportacionCatalogo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Actualizadas")
                        .HasColumnType("integer")
                        .HasColumnName("actualizadas");

                    b.Property<DateTimeOffset>("AplicadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aplicado_en");

                    b.Property<string>("AplicadoPor")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("aplicado_por");

                    b.Property<string>("ArchivoNombre")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("archivo_nombre");

                    b.Property<int>("Creadas")
                        .HasColumnType("integer")
                        .HasColumnName("creadas");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("fuente");

                    b.Property<string>("HuellaSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("huella_sha256");

                    b.Property<int>("SinCambios")
                        .HasColumnType("integer")
                        .HasColumnName("sin_cambios");

                    b.Property<int>("TotalFilas")
                        .HasColumnType("integer")
                        .HasColumnName("total_filas");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_importaciones_catalogo");

                    b.HasIndex("EmpresaId", "HuellaSha256")
                        .IsUnique()
                        .HasDatabaseName("ux_importaciones_huella");

                    b.ToTable("importaciones_catalogo", "contabilidad");
                });

            modelBuilder.Entity("Millet.SharedKernel.Domain.Audit.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_email");

                    b.Property<string>("ActorNombre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("actor_nombre");

                    b.Property<string>("ActorTipo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_tipo");

                    b.Property<Guid?>("AggregateRootId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_root_id");

                    b.Property<string>("Cambios")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cambios");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entidad");

                    b.Property<string>("EntidadEtiqueta")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entidad_etiqueta");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<bool>("EsBulk")
                        .HasColumnType("boolean")
                        .HasColumnName("es_bulk");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<string>("Metadatos")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadatos");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("modulo");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operacion");

                    b.Property<string>("Resumen")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("resumen");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id", "Timestamp")
                        .HasName("pk_audit_log");

                    b.HasIndex("ActorTipo", "Timestamp")
                        .HasDatabaseName("ix_audit_log_actor_tipo_timestamp");

                    b.HasIndex("EmpresaId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_empresa_id_timestamp");

                    b.HasIndex("UsuarioId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_usuario_id_timestamp");

                    b.HasIndex("Modulo", "AggregateRootId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_modulo_aggregate_root_id_timestamp");

                    b.HasIndex("Modulo", "Entidad", "EntidadId")
                        .HasDatabaseName("ix_audit_log_modulo_entidad_entidad_id");

                    b.ToTable("audit_log", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Millet.Contabilidad.Domain.CuentaContable", b =>
                {
                    b.HasOne("Millet.Contabilidad.Domain.CuentaContable", null)
                        .WithMany()
                        .HasForeignKey("PadreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cuentas_contables_cuentas_contables_padre_id");

                    b.HasOne("Millet.Contabilidad.Domain.CuentaContable", null)
                        .WithMany()
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cuentas_contables_cuentas_contables_rubro_id");
                });

            modelBuilder.Entity("Millet.Contabilidad.Domain.CuentaContableOrigen", b =>
                {
                    b.HasOne("Millet.Contabilidad.Domain.CuentaContable", null)
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cuentas_contables_origen_cuentas_contables_cuenta_id");

                    b.HasOne("Millet.Contabilidad.Domain.ImportacionCatalogo", null)
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cuentas_contables_origen_importaciones_lote_id");
                });

            modelBuilder.Entity("Millet.Contabilidad.Domain.CuentaContableUso", b =>
                {
                    b.HasOne("Millet.Contabilidad.Domain.CuentaContable", null)
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cuentas_contables_uso_cuentas_contables_cuenta_id");
                });
#pragma warning restore 612, 618
        }
    }
}
