// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Millet.Integraciones.Fiscal.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Millet.Integraciones.Fiscal.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IntegracionesFiscalDbContext))]
    [Migration("20260525213747_Pr10_RfcReceptorFiel")]
    partial class Pr10_RfcReceptorFiel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("integraciones_fiscal")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Millet.Integraciones.Fiscal.Domain.ConfiguracionPac", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<byte[]>("ApiKeyCifrado")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("api_key_cifrado");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("api_key_hash");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<int>("CircuitBreakerDuracionSegundos")
                        .HasColumnType("integer")
                        .HasColumnName("circuit_breaker_duracion_segundos");

                    b.Property<int>("CircuitBreakerFailures")
                        .HasColumnType("integer")
                        .HasColumnName("circuit_breaker_failures");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DescargaBackfillHoras")
                        .HasColumnType("integer")
                        .HasColumnName("descarga_backfill_horas");

                    b.Property<int>("DescargaIntervaloSegundos")
                        .HasColumnType("integer")
                        .HasColumnName("descarga_intervalo_segundos");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<short>("Proveedor")
                        .HasColumnType("smallint")
                        .HasColumnName("proveedor");

                    b.Property<int>("RefreshBatchSize")
                        .HasColumnType("integer")
                        .HasColumnName("refresh_batch_size");

                    b.Property<int>("RefreshIntervaloSegundos")
                        .HasColumnType("integer")
                        .HasColumnName("refresh_intervalo_segundos");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<int>("TimeoutConsultaSegundos")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_consulta_segundos");

                    b.Property<int>("TimeoutDescargaSegundos")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_descarga_segundos");

                    b.Property<DateTimeOffset?>("UltimaRotacionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_rotacion_at");

                    b.Property<DateTimeOffset?>("UltimaTestConexionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_test_conexion_at");

                    b.Property<bool?>("UltimaTestConexionExitosa")
                        .HasColumnType("boolean")
                        .HasColumnName("ultima_test_conexion_exitosa");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_configuracion_pac");

                    b.HasIndex("Activo")
                        .HasDatabaseName("ix_configuracion_pac_activo")
                        .HasFilter("activo = true AND deleted_at IS NULL");

                    b.HasIndex("EmpresaId", "Proveedor")
                        .IsUnique()
                        .HasDatabaseName("uq_configuracion_pac_empresa_proveedor");

                    b.ToTable("configuracion_pac", "integraciones_fiscal", t =>
                        {
                            t.HasCheckConstraint("ck_configuracion_pac_proveedor", "proveedor BETWEEN 1 AND 1");
                        });
                });

            modelBuilder.Entity("Millet.Integraciones.Fiscal.Domain.DownloadRuleExterna", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<short>("DownloadType")
                        .HasColumnType("smallint")
                        .HasColumnName("download_type");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("RfcReceptorId")
                        .HasColumnType("uuid")
                        .HasColumnName("rfc_receptor_id");

                    b.Property<string>("RuleIdExterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_id_externo");

                    b.Property<short>("SatInvoiceStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("sat_invoice_status");

                    b.Property<short>("SatQueryType")
                        .HasColumnType("smallint")
                        .HasColumnName("sat_query_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_download_rules_externas");

                    b.HasIndex("EmpresaId", "Activa")
                        .HasDatabaseName("ix_download_rules_empresa_activa")
                        .HasFilter("activa = true AND deleted_at IS NULL");

                    b.HasIndex("RfcReceptorId", "SatQueryType", "DownloadType", "SatInvoiceStatus")
                        .IsUnique()
                        .HasDatabaseName("uq_download_rules_combo");

                    b.ToTable("download_rules_externas", "integraciones_fiscal");
                });

            modelBuilder.Entity("Millet.Integraciones.Fiscal.Domain.RfcReceptor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CerFileIdExterno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cer_file_id_externo");

                    b.Property<DateTimeOffset?>("CheckpointDescargaAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checkpoint_descarga_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("DescargaHabilitada")
                        .HasColumnType("boolean")
                        .HasColumnName("descarga_habilitada");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTimeOffset?>("FielSubidaAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fiel_subida_at");

                    b.Property<DateTimeOffset?>("FielValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fiel_valid_from");

                    b.Property<DateTimeOffset?>("FielValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fiel_valid_to");

                    b.Property<string>("KeyFileIdExterno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key_file_id_externo");

                    b.Property<string>("PersonIdExterno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("person_id_externo");

                    b.Property<bool>("RefreshHabilitada")
                        .HasColumnType("boolean")
                        .HasColumnName("refresh_habilitada");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("rfc");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_rfcs_receptores");

                    b.HasIndex("EmpresaId", "DescargaHabilitada")
                        .HasDatabaseName("ix_rfcs_receptores_empresa_descarga")
                        .HasFilter("descarga_habilitada = true AND deleted_at IS NULL");

                    b.HasIndex("EmpresaId", "Rfc")
                        .IsUnique()
                        .HasDatabaseName("uq_rfcs_receptores_empresa_rfc");

                    b.ToTable("rfcs_receptores", "integraciones_fiscal", t =>
                        {
                            t.HasCheckConstraint("ck_rfcs_receptores_longitud", "char_length(rfc) BETWEEN 12 AND 13");
                        });
                });

            modelBuilder.Entity("Millet.Integraciones.Fiscal.Domain.SolicitudDescarga", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptsPoll")
                        .HasColumnType("integer")
                        .HasColumnName("attempts_poll");

                    b.Property<DateTimeOffset?>("CerradaAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cerrada_at");

                    b.Property<DateTimeOffset?>("CosechadaAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cosechada_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DownloadRequestStatusExterno")
                        .HasColumnType("integer")
                        .HasColumnName("download_request_status_externo");

                    b.Property<Guid>("DownloadRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("download_rule_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("ErrorCodigo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("error_codigo");

                    b.Property<string>("ErrorMensaje")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_mensaje");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<int?>("InvoiceCount")
                        .HasColumnType("integer")
                        .HasColumnName("invoice_count");

                    b.Property<DateTimeOffset?>("LastPollAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_poll_at");

                    b.Property<DateTimeOffset>("NextPollAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_poll_at");

                    b.Property<string>("RequestIdExterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("request_id_externo");

                    b.Property<int?>("SatRequestStatusExterno")
                        .HasColumnType("integer")
                        .HasColumnName("sat_request_status_externo");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_solicitudes_descarga");

                    b.HasIndex("RequestIdExterno")
                        .IsUnique()
                        .HasDatabaseName("uq_solicitudes_request_externo");

                    b.HasIndex("Estado", "NextPollAt")
                        .HasDatabaseName("ix_solicitudes_descarga_next_poll")
                        .HasFilter("estado IN (2, 3, 4) AND deleted_at IS NULL");

                    b.HasIndex("EmpresaId", "DownloadRuleId", "StartDate")
                        .HasDatabaseName("ix_solicitudes_empresa_rule_start");

                    b.ToTable("solicitudes_descarga", "integraciones_fiscal");
                });

            modelBuilder.Entity("Millet.SharedKernel.Domain.Audit.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("AggregateRootId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_root_id");

                    b.Property<string>("Cambios")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cambios");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entidad");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<bool>("EsBulk")
                        .HasColumnType("boolean")
                        .HasColumnName("es_bulk");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<string>("Metadatos")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadatos");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("modulo");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operacion");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id", "Timestamp")
                        .HasName("pk_audit_log");

                    b.HasIndex("EmpresaId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_empresa_id_timestamp");

                    b.HasIndex("UsuarioId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_usuario_id_timestamp");

                    b.HasIndex("Modulo", "AggregateRootId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_modulo_aggregate_root_id_timestamp");

                    b.HasIndex("Modulo", "Entidad", "EntidadId")
                        .HasDatabaseName("ix_audit_log_modulo_entidad_entidad_id");

                    b.ToTable("audit_log", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Millet.SharedKernel.Infrastructure.Outbox.IntegrationEventOutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("IntegrationEmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_empresa_id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_integration_events_outbox");

                    b.HasIndex("IntegrationEmpresaId")
                        .HasDatabaseName("ix_integration_events_outbox_integration_empresa_id");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_integration_events_outbox_pending")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("integration_events_outbox", "integraciones_fiscal");
                });
#pragma warning restore 612, 618
        }
    }
}
