// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Millet.CentrosCosto.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Millet.CentrosCosto.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CentrosCostoDbContext))]
    [Migration("20260714221349_CentrosCostoEsquemaInicial")]
    partial class CentrosCostoEsquemaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("centros_costo")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Millet.CentrosCosto.Domain.Departamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clave");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<short>("Estatus")
                        .HasColumnType("smallint")
                        .HasColumnName("estatus");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("SucursalCentroCostoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_centro_costo_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_departamentos");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("ux_departamentos_clave");

                    b.HasIndex("Estatus")
                        .HasDatabaseName("ix_departamentos_estatus");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("ix_departamentos_grupo_id");

                    b.HasIndex("SucursalCentroCostoId")
                        .HasDatabaseName("ix_departamentos_sucursal_centro_costo_id");

                    b.ToTable("departamentos", "centros_costo", t =>
                        {
                            t.HasCheckConstraint("ck_departamentos_estatus", "estatus BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Millet.CentrosCosto.Domain.Equipo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clave");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("DepartamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("departamento_id");

                    b.Property<short>("Estatus")
                        .HasColumnType("smallint")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("SubgrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("subgrupo_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_equipos");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("ux_equipos_clave");

                    b.HasIndex("DepartamentoId")
                        .HasDatabaseName("ix_equipos_departamento_id");

                    b.HasIndex("Estatus")
                        .HasDatabaseName("ix_equipos_estatus");

                    b.HasIndex("SubgrupoId")
                        .HasDatabaseName("ix_equipos_subgrupo_id");

                    b.ToTable("equipos", "centros_costo", t =>
                        {
                            t.HasCheckConstraint("ck_equipos_estatus", "estatus BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Millet.CentrosCosto.Domain.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<short>("Estatus")
                        .HasColumnType("smallint")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_grupos");

                    b.HasIndex("Estatus")
                        .HasDatabaseName("ix_grupos_estatus");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_grupos_nombre");

                    b.ToTable("grupos", "centros_costo", t =>
                        {
                            t.HasCheckConstraint("ck_grupos_estatus", "estatus BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Millet.CentrosCosto.Domain.Subgrupo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<short>("Estatus")
                        .HasColumnType("smallint")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_subgrupos");

                    b.HasIndex("Estatus")
                        .HasDatabaseName("ix_subgrupos_estatus");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_subgrupos_nombre");

                    b.ToTable("subgrupos", "centros_costo", t =>
                        {
                            t.HasCheckConstraint("ck_subgrupos_estatus", "estatus BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Millet.CentrosCosto.Domain.SucursalCentroCosto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClaveCeCo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("clave_ceco");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<short>("Estatus")
                        .HasColumnType("smallint")
                        .HasColumnName("estatus");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_sucursales_ceco");

                    b.HasIndex("ClaveCeCo")
                        .IsUnique()
                        .HasDatabaseName("ux_sucursales_ceco_clave_ceco");

                    b.HasIndex("Estatus")
                        .HasDatabaseName("ix_sucursales_ceco_estatus");

                    b.HasIndex("SucursalId")
                        .IsUnique()
                        .HasDatabaseName("ux_sucursales_ceco_sucursal_id");

                    b.ToTable("sucursales_ceco", "centros_costo", t =>
                        {
                            t.HasCheckConstraint("ck_sucursales_ceco_estatus", "estatus BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Millet.SharedKernel.Domain.Audit.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("AggregateRootId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_root_id");

                    b.Property<string>("Cambios")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cambios");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entidad");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<bool>("EsBulk")
                        .HasColumnType("boolean")
                        .HasColumnName("es_bulk");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<string>("Metadatos")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadatos");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("modulo");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operacion");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id", "Timestamp")
                        .HasName("pk_audit_log");

                    b.HasIndex("EmpresaId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_empresa_id_timestamp");

                    b.HasIndex("UsuarioId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_usuario_id_timestamp");

                    b.HasIndex("Modulo", "AggregateRootId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_modulo_aggregate_root_id_timestamp");

                    b.HasIndex("Modulo", "Entidad", "EntidadId")
                        .HasDatabaseName("ix_audit_log_modulo_entidad_entidad_id");

                    b.ToTable("audit_log", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Millet.CentrosCosto.Domain.Departamento", b =>
                {
                    b.HasOne("Millet.CentrosCosto.Domain.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_departamentos_grupos_grupo_id");

                    b.HasOne("Millet.CentrosCosto.Domain.SucursalCentroCosto", null)
                        .WithMany()
                        .HasForeignKey("SucursalCentroCostoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_departamentos_sucursales_ceco_sucursal_centro_costo_id");
                });

            modelBuilder.Entity("Millet.CentrosCosto.Domain.Equipo", b =>
                {
                    b.HasOne("Millet.CentrosCosto.Domain.Departamento", null)
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_equipos_departamentos_departamento_id");

                    b.HasOne("Millet.CentrosCosto.Domain.Subgrupo", null)
                        .WithMany()
                        .HasForeignKey("SubgrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_equipos_subgrupos_subgrupo_id");
                });
#pragma warning restore 612, 618
        }
    }
}
