import {
  BriefcaseBusiness,
  Building2,
  Hash,
  History,
  IdCard,
  MapPin,
  Network,
  SlidersHorizontal,
  Store,
} from 'lucide-react';
import { PermisosCanonicos } from '@/lib/auth/permission-codes';
import type { AdminSection } from '@/lib/admin/registry';

/**
 * Cards del área transversal de Administración (organización) que se
 * exponen en <c>/admin</c>. UF-Admin-PR6 publica la card de Series y
 * folios, UF-Admin-PR7 cierra el módulo con Parámetros y Auditoría.
 * Todas linkean a UIs dedicadas (<c>displayMode: 'custom'</c>).
 *
 * Mi empresa expone la configuración fiscal de la única razón social.
 */
export const administracionAdminCards: readonly AdminSection[] = [
  {
    id: 'admin-mi-empresa',
    modulo: 'admin',
    titulo: 'Mi empresa',
    descripcion: 'Datos fiscales y sucursales de Millet',
    icon: Building2,
    href: '/admin/mi-empresa',
    permisoRequerido: PermisosCanonicos.AdminEmpresasLeer,
    orden: 5,
    grupo: 'organizacion',
    displayMode: 'custom',
  },
  {
    id: 'admin-sucursales',
    modulo: 'admin',
    titulo: 'Sucursales',
    descripcion: 'Dónde opera Millet y quién ve cada sucursal',
    icon: MapPin,
    href: '/admin/sucursales',
    permisoRequerido: PermisosCanonicos.AdminEmpresasSucursalesGestionar,
    orden: 10,
    grupo: 'organizacion',
    displayMode: 'custom',
  },
  {
    id: 'admin-departamentos',
    modulo: 'admin',
    titulo: 'Departamentos',
    descripcion: 'Áreas de trabajo y en qué sucursales están',
    icon: Network,
    href: '/admin/departamentos',
    permisoRequerido: PermisosCanonicos.AdminDepartamentosGestionar,
    orden: 11,
    grupo: 'organizacion',
    displayMode: 'custom',
  },
  {
    id: 'admin-canales-venta',
    modulo: 'admin',
    titulo: 'Canales de venta',
    descripcion: 'Canales con los que se facturan los pedidos de A+W',
    icon: Store,
    href: '/admin/canales-venta',
    permisoRequerido: PermisosCanonicos.AdminEmpresasSucursalesGestionar,
    orden: 15,
    grupo: 'organizacion',
    displayMode: 'custom',
  },
  {
    id: 'admin-puestos',
    modulo: 'admin',
    titulo: 'Puestos',
    descripcion: 'Puestos de trabajo y sus reglas de viáticos',
    icon: BriefcaseBusiness,
    href: '/admin/puestos',
    permisoRequerido: PermisosCanonicos.AdminPuestosGestionar,
    orden: 16,
    grupo: 'organizacion',
    displayMode: 'custom',
  },
  {
    id: 'admin-empleados',
    modulo: 'admin',
    titulo: 'Empleados',
    descripcion: 'Personas de Millet, su jefe directo y responsables de gastos',
    icon: IdCard,
    href: '/admin/empleados',
    permisoRequerido: PermisosCanonicos.AdminEmpleadosGestionar,
    orden: 17,
    grupo: 'organizacion',
    displayMode: 'custom',
  },
  {
    id: 'admin-series',
    modulo: 'admin',
    titulo: 'Series y folios',
    descripcion: 'Series y folios de cada documento por sucursal',
    icon: Hash,
    href: '/admin/series',
    permisoRequerido: PermisosCanonicos.AdminSeriesGestionar,
    orden: 20,
    grupo: 'facturacion_reglas',
    displayMode: 'custom',
  },
  {
    id: 'admin-parametros',
    modulo: 'admin',
    titulo: 'Parámetros del sistema',
    descripcion: 'Montos, tolerancias y reglas generales del ERP',
    icon: SlidersHorizontal,
    href: '/admin/parametros',
    permisoRequerido: PermisosCanonicos.AdminParametrosLeer,
    orden: 30,
    grupo: 'facturacion_reglas',
    displayMode: 'custom',
  },
  {
    id: 'admin-auditoria',
    modulo: 'admin',
    titulo: 'Auditoría',
    descripcion: 'Quién cambió qué y cuándo',
    icon: History,
    href: '/admin/auditoria',
    permisoRequerido: PermisosCanonicos.AdminAuditoriaLeer,
    orden: 40,
    grupo: 'identidad',
    displayMode: 'custom',
  },
];
