// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Millet.Almacen.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Millet.Almacen.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AlmacenDbContext))]
    [Migration("20260523021200_EventosProcesados")]
    partial class EventosProcesados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("almacen")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Millet.Almacen.Domain.Catalogo.Almacen", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clave");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<short>("Estatus")
                        .HasColumnType("smallint")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_almacenes");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("ix_almacenes_clave");

                    b.HasIndex("Estatus")
                        .HasDatabaseName("ix_almacenes_estatus");

                    b.HasIndex("SucursalId")
                        .HasDatabaseName("ix_almacenes_sucursal_id");

                    b.ToTable("almacenes", "almacen", t =>
                        {
                            t.HasCheckConstraint("ck_almacenes_estatus", "estatus BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Millet.Almacen.Domain.Catalogo.SubAlmacen", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clave");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<short>("Estatus")
                        .HasColumnType("smallint")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("nombre");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_sub_almacenes");

                    b.HasIndex("AlmacenId")
                        .HasDatabaseName("ix_sub_almacenes_almacen_id");

                    b.HasIndex("Estatus")
                        .HasDatabaseName("ix_sub_almacenes_estatus");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("ix_sub_almacenes_tipo");

                    b.HasIndex("AlmacenId", "Clave")
                        .IsUnique()
                        .HasDatabaseName("ux_sub_almacenes_almacen_clave");

                    b.ToTable("sub_almacenes", "almacen", t =>
                        {
                            t.HasCheckConstraint("ck_sub_almacenes_estatus", "estatus BETWEEN 0 AND 2");

                            t.HasCheckConstraint("ck_sub_almacenes_tipo", "tipo BETWEEN 0 AND 3");
                        });
                });

            modelBuilder.Entity("Millet.Almacen.Domain.Idempotencia.EventoProcesado", b =>
                {
                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<string>("EventoTipo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("evento_tipo");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<DateTimeOffset>("ProcesadoAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("procesado_at");

                    b.HasKey("EventoId", "EventoTipo")
                        .HasName("pk_eventos_procesados");

                    b.HasIndex("ProcesadoAt")
                        .HasDatabaseName("ix_eventos_procesados_at");

                    b.ToTable("eventos_procesados", "almacen");
                });

            modelBuilder.Entity("Millet.Almacen.Domain.Movimientos.FolioSecuenciaMovimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("prefijo");

                    b.Property<int>("UltimoNumero")
                        .HasColumnType("integer")
                        .HasColumnName("ultimo_numero");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_folio_secuencias_movimiento");

                    b.HasIndex("Prefijo", "Anio")
                        .IsUnique()
                        .HasDatabaseName("ux_folio_secuencias_prefijo_anio");

                    b.ToTable("folio_secuencias_movimiento", "almacen", t =>
                        {
                            t.HasCheckConstraint("ck_folio_secuencias_ultimo_no_negativo", "ultimo_numero >= 0");
                        });
                });

            modelBuilder.Entity("Millet.Almacen.Domain.Movimientos.LineaMovimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("articulo_id");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("cantidad");

                    b.Property<decimal?>("CantidadRealContada")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("cantidad_real_contada");

                    b.Property<decimal?>("CantidadTeoricaAlContar")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("cantidad_teorica_al_contar");

                    b.Property<Guid?>("CentroCostoId")
                        .HasColumnType("uuid")
                        .HasColumnName("centro_costo_id");

                    b.Property<string>("ComentarioLinea")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comentario_linea");

                    b.Property<decimal>("CostoUnitarioMxn")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("costo_unitario_mxn");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("LineaFacturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("linea_factura_id");

                    b.Property<string>("MonedaOriginal")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moneda_original");

                    b.Property<decimal>("MontoTotalMxn")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("monto_total_mxn");

                    b.Property<Guid>("MovimientoId")
                        .HasColumnType("uuid")
                        .HasColumnName("movimiento_id");

                    b.Property<int>("Posicion")
                        .HasColumnType("integer")
                        .HasColumnName("posicion");

                    b.Property<Guid?>("ProyectoId")
                        .HasColumnType("uuid")
                        .HasColumnName("proyecto_id");

                    b.Property<decimal?>("TipoCambioAplicado")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("tipo_cambio_aplicado");

                    b.Property<string>("UbicacionReferencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ubicacion_referencia");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidad_medida");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_lineas_movimiento");

                    b.HasIndex("ArticuloId")
                        .HasDatabaseName("ix_lineas_movimiento_articulo_id");

                    b.HasIndex("MovimientoId")
                        .HasDatabaseName("ix_lineas_movimiento_movimiento_id");

                    b.ToTable("lineas_movimiento", "almacen", t =>
                        {
                            t.HasCheckConstraint("ck_lineas_cantidad_positiva", "cantidad > 0");

                            t.HasCheckConstraint("ck_lineas_costo_no_negativo", "costo_unitario_mxn >= 0");
                        });
                });

            modelBuilder.Entity("Millet.Almacen.Domain.Movimientos.MovimientoInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CfdiRecibidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cfdi_recibido_id");

                    b.Property<string>("ComentarioLibre")
                        .HasColumnType("text")
                        .HasColumnName("comentario_libre");

                    b.Property<Guid?>("ConteoId")
                        .HasColumnType("uuid")
                        .HasColumnName("conteo_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<string>("EstadoMaterial")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado_material");

                    b.Property<Guid?>("FacturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("factura_id");

                    b.Property<Guid?>("FacturaIdOrigenDiff")
                        .HasColumnType("uuid")
                        .HasColumnName("factura_id_origen_diff");

                    b.Property<DateTimeOffset?>("FechaLimiteRegularizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_limite_regularizacion");

                    b.Property<DateOnly>("FechaMovimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_movimiento");

                    b.Property<DateTimeOffset>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Folio")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("folio");

                    b.Property<Guid?>("MaquinaDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("maquina_destino_id");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo");

                    b.Property<Guid?>("OcId")
                        .HasColumnType("uuid")
                        .HasColumnName("oc_id");

                    b.Property<Guid?>("OcLineaId")
                        .HasColumnType("uuid")
                        .HasColumnName("oc_linea_id");

                    b.Property<string>("PackingListBlobRef")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("packing_list_blob_ref");

                    b.Property<bool>("PendienteRegularizacion")
                        .HasColumnType("boolean")
                        .HasColumnName("pendiente_regularizacion");

                    b.Property<Guid?>("PersonaDestinatariaId")
                        .HasColumnType("uuid")
                        .HasColumnName("persona_destinataria_id");

                    b.Property<Guid?>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<Guid?>("RecepcionOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("recepcion_origen_id");

                    b.Property<DateTimeOffset?>("RegistradoAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registrado_at");

                    b.Property<Guid?>("RegistradoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("registrado_por");

                    b.Property<Guid?>("RqId")
                        .HasColumnType("uuid")
                        .HasColumnName("rq_id");

                    b.Property<Guid?>("RqRegularizadoraId")
                        .HasColumnType("uuid")
                        .HasColumnName("rq_regularizadora_id");

                    b.Property<Guid?>("SalidaOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("salida_origen_id");

                    b.Property<Guid>("SubAlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_almacen_id");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("ValeBlobRef")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("vale_blob_ref");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_movimientos_inventario");

                    b.HasIndex("FechaLimiteRegularizacion")
                        .HasDatabaseName("ix_movimientos_vale_pendientes")
                        .HasFilter("tipo = 2 AND pendiente_regularizacion = true");

                    b.HasIndex("Folio")
                        .IsUnique()
                        .HasDatabaseName("ux_movimientos_folio")
                        .HasFilter("folio IS NOT NULL");

                    b.HasIndex("OcId", "Tipo")
                        .HasDatabaseName("ix_movimientos_por_oc")
                        .HasFilter("oc_id IS NOT NULL");

                    b.HasIndex("RqId", "Tipo")
                        .HasDatabaseName("ix_movimientos_por_rq")
                        .HasFilter("rq_id IS NOT NULL");

                    b.HasIndex("SubAlmacenId", "FechaMovimiento")
                        .HasDatabaseName("ix_movimientos_recepciones")
                        .HasFilter("tipo = 0 AND estado = 2");

                    b.ToTable("movimientos_inventario", "almacen", t =>
                        {
                            t.HasCheckConstraint("ck_movimientos_estado", "estado BETWEEN 0 AND 3");

                            t.HasCheckConstraint("ck_movimientos_tipo", "tipo BETWEEN 0 AND 9");
                        });
                });

            modelBuilder.Entity("Millet.Almacen.Domain.Saldos.SaldoInventario", b =>
                {
                    b.Property<Guid>("SubAlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_almacen_id");

                    b.Property<Guid>("ArticuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("articulo_id");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("CantidadDisponible")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("cantidad_disponible")
                        .HasComputedColumnSql("cantidad - cantidad_reservada", true);

                    b.Property<decimal>("CantidadReservada")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("cantidad_reservada");

                    b.Property<decimal>("CostoPromedioMxn")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("costo_promedio_mxn");

                    b.Property<DateTimeOffset>("UltimaActualizacionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion_at");

                    b.Property<Guid?>("UltimoMovimientoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ultimo_movimiento_id");

                    b.Property<decimal>("ValorInventarioMxn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor_inventario_mxn")
                        .HasComputedColumnSql("cantidad * costo_promedio_mxn", true);

                    b.HasKey("SubAlmacenId", "ArticuloId")
                        .HasName("pk_saldos_inventario");

                    b.HasIndex("ArticuloId", "SubAlmacenId")
                        .HasDatabaseName("ix_saldos_con_stock")
                        .HasFilter("cantidad > 0");

                    b.HasIndex("SubAlmacenId", "ArticuloId")
                        .HasDatabaseName("ix_saldos_sub_almacen");

                    b.ToTable("saldos_inventario", "almacen", t =>
                        {
                            t.HasCheckConstraint("ck_saldos_cantidad_no_negativa", "cantidad >= 0");

                            t.HasCheckConstraint("ck_saldos_reservada_no_excede", "cantidad_reservada <= cantidad");

                            t.HasCheckConstraint("ck_saldos_reservada_no_negativa", "cantidad_reservada >= 0");
                        });
                });

            modelBuilder.Entity("Millet.SharedKernel.Domain.Audit.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("AggregateRootId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_root_id");

                    b.Property<string>("Cambios")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cambios");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entidad");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<bool>("EsBulk")
                        .HasColumnType("boolean")
                        .HasColumnName("es_bulk");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<string>("Metadatos")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadatos");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("modulo");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operacion");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id", "Timestamp")
                        .HasName("pk_audit_log");

                    b.HasIndex("EmpresaId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_empresa_id_timestamp");

                    b.HasIndex("UsuarioId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_usuario_id_timestamp");

                    b.HasIndex("Modulo", "AggregateRootId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_modulo_aggregate_root_id_timestamp");

                    b.HasIndex("Modulo", "Entidad", "EntidadId")
                        .HasDatabaseName("ix_audit_log_modulo_entidad_entidad_id");

                    b.ToTable("audit_log", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Millet.SharedKernel.Infrastructure.Outbox.IntegrationEventOutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("IntegrationEmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_empresa_id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_integration_events_outbox");

                    b.HasIndex("IntegrationEmpresaId")
                        .HasDatabaseName("ix_integration_events_outbox_integration_empresa_id");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_integration_events_outbox_pending")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("integration_events_outbox", "almacen");
                });

            modelBuilder.Entity("Millet.Almacen.Domain.Catalogo.SubAlmacen", b =>
                {
                    b.HasOne("Millet.Almacen.Domain.Catalogo.Almacen", null)
                        .WithMany("SubAlmacenes")
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sub_almacenes_almacenes_almacen_id");
                });

            modelBuilder.Entity("Millet.Almacen.Domain.Movimientos.LineaMovimiento", b =>
                {
                    b.HasOne("Millet.Almacen.Domain.Movimientos.MovimientoInventario", null)
                        .WithMany("Lineas")
                        .HasForeignKey("MovimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lineas_movimiento_movimientos_inventario_movimiento_id");
                });

            modelBuilder.Entity("Millet.Almacen.Domain.Movimientos.MovimientoInventario", b =>
                {
                    b.HasOne("Millet.Almacen.Domain.Catalogo.SubAlmacen", null)
                        .WithMany()
                        .HasForeignKey("SubAlmacenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_inventario_sub_almacenes_sub_almacen_id");
                });

            modelBuilder.Entity("Millet.Almacen.Domain.Saldos.SaldoInventario", b =>
                {
                    b.HasOne("Millet.Almacen.Domain.Catalogo.SubAlmacen", null)
                        .WithMany()
                        .HasForeignKey("SubAlmacenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_saldos_inventario_sub_almacenes_sub_almacen_id");
                });

            modelBuilder.Entity("Millet.Almacen.Domain.Catalogo.Almacen", b =>
                {
                    b.Navigation("SubAlmacenes");
                });

            modelBuilder.Entity("Millet.Almacen.Domain.Movimientos.MovimientoInventario", b =>
                {
                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
