// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Millet.Compras.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Millet.Compras.Infrastructure.Migrations
{
    [DbContext(typeof(ComprasDbContext))]
    [Migration("20260511180449_OrdenesCompraTabla")]
    partial class OrdenesCompraTabla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("compras")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Millet.Compras.Domain.AprobadorDepartamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepartamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("departamento_id");

                    b.Property<Guid>("DesignadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("designado_por");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo");

                    b.Property<short>("Rol")
                        .HasColumnType("smallint")
                        .HasColumnName("rol");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<DateTimeOffset>("VigenteDesde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigente_desde");

                    b.Property<DateTimeOffset?>("VigenteHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigente_hasta");

                    b.HasKey("Id")
                        .HasName("pk_aprobadores_departamento");

                    b.HasIndex("EmpresaId", "UsuarioId")
                        .HasDatabaseName("ix_aprobadores_departamento_usuario_vigente")
                        .HasFilter("vigente_hasta IS NULL");

                    b.HasIndex("EmpresaId", "DepartamentoId", "Rol")
                        .IsUnique()
                        .HasDatabaseName("ux_aprobadores_departamento_vigente")
                        .HasFilter("vigente_hasta IS NULL");

                    b.HasIndex("EmpresaId", "DepartamentoId", "Rol", "VigenteDesde")
                        .IsDescending(false, false, false, true)
                        .HasDatabaseName("ix_aprobadores_departamento_historico");

                    b.ToTable("aprobadores_departamento", "compras", t =>
                        {
                            t.HasCheckConstraint("ck_aprobadores_departamento_rol", "rol BETWEEN 0 AND 2");

                            t.HasCheckConstraint("ck_aprobadores_departamento_vigencia", "vigente_hasta IS NULL OR vigente_hasta >= vigente_desde");
                        });
                });

            modelBuilder.Entity("Millet.Compras.Domain.Autorizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<short>("Nivel")
                        .HasColumnType("smallint")
                        .HasColumnName("nivel");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notas");

                    b.Property<Guid>("RequisicionId")
                        .HasColumnType("uuid")
                        .HasColumnName("requisicion_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_requisicion_autorizaciones");

                    b.HasIndex("RequisicionId", "Nivel")
                        .IsUnique()
                        .HasDatabaseName("ix_requisicion_autorizaciones_requisicion_id_nivel");

                    b.HasIndex("UsuarioId", "FechaHora")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_requisicion_autorizaciones_usuario_id_fecha_hora");

                    b.ToTable("requisicion_autorizaciones", "compras", t =>
                        {
                            t.HasCheckConstraint("ck_requisicion_autorizaciones_nivel", "nivel IN (1, 2)");
                        });
                });

            modelBuilder.Entity("Millet.Compras.Domain.FolioSecuencia", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_id");

                    b.Property<short>("Anio")
                        .HasColumnType("smallint")
                        .HasColumnName("anio");

                    b.Property<int>("Siguiente")
                        .HasColumnType("integer")
                        .HasColumnName("siguiente");

                    b.HasKey("EmpresaId", "SucursalId", "Anio")
                        .HasName("pk_folio_secuencias");

                    b.ToTable("folio_secuencias", "compras");
                });

            modelBuilder.Entity("Millet.Compras.Domain.LineaRequisicion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("articulo_id");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 5)
                        .HasColumnType("numeric(18,5)")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("CantidadDeAlmacen")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 5)
                        .HasColumnType("numeric(18,5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("cant_de_almacen");

                    b.Property<decimal>("CantidadDeCompra")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 5)
                        .HasColumnType("numeric(18,5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("cant_de_compra");

                    b.Property<decimal>("CantidadRecibida")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 5)
                        .HasColumnType("numeric(18,5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("cant_recibida");

                    b.Property<Guid?>("CentroCostoId")
                        .HasColumnType("uuid")
                        .HasColumnName("centro_costo_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CuentaContableId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_contable_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateOnly?>("FechaRequerida")
                        .HasColumnType("date")
                        .HasColumnName("fecha_requerida");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notas");

                    b.Property<short>("Posicion")
                        .HasColumnType("smallint")
                        .HasColumnName("posicion");

                    b.Property<string>("Proyecto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("proyecto");

                    b.Property<Guid>("RequisicionId")
                        .HasColumnType("uuid")
                        .HasColumnName("requisicion_id");

                    b.Property<Guid?>("ReservaId")
                        .HasColumnType("uuid")
                        .HasColumnName("reserva_id");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidad_medida");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty<Dictionary<string, object>>("PrecioEstimado", "Millet.Compras.Domain.LineaRequisicion.PrecioEstimado#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("precio_estimado");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("MXN")
                                .HasColumnName("moneda");
                        });

                    b.HasKey("Id")
                        .HasName("pk_requisicion_lineas");

                    b.HasIndex("RequisicionId", "Posicion")
                        .IsUnique()
                        .HasDatabaseName("ix_requisicion_lineas_requisicion_id_posicion");

                    b.ToTable("requisicion_lineas", "compras", t =>
                        {
                            t.HasCheckConstraint("ck_requisicion_lineas_cantidad_positiva", "cantidad > 0");

                            t.HasCheckConstraint("ck_requisicion_lineas_cubrimiento_no_excede", "cant_de_almacen + cant_de_compra <= cantidad");

                            t.HasCheckConstraint("ck_requisicion_lineas_moneda_iso", "moneda ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_requisicion_lineas_recibida_no_excede_compra", "cant_recibida <= cant_de_compra");
                        });
                });

            modelBuilder.Entity("Millet.Compras.Domain.MotivoRechazo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<short>("AplicaA")
                        .HasColumnType("smallint")
                        .HasColumnName("aplica_a");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clave");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("PermiteTextoLibre")
                        .HasColumnType("boolean")
                        .HasColumnName("permite_texto_libre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_motivos_rechazo");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("ix_motivos_rechazo_clave");

                    b.ToTable("motivos_rechazo", "compras", t =>
                        {
                            t.HasCheckConstraint("ck_motivos_rechazo_aplica_a", "aplica_a BETWEEN 1 AND 7");
                        });
                });

            modelBuilder.Entity("Millet.Compras.Domain.Oc.FolioSecuenciaOc", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_id");

                    b.Property<short>("Anio")
                        .HasColumnType("smallint")
                        .HasColumnName("anio");

                    b.Property<long>("Siguiente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("siguiente");

                    b.HasKey("EmpresaId", "SucursalId", "Anio")
                        .HasName("pk_folio_secuencias_oc");

                    b.ToTable("folio_secuencias_oc", "compras");
                });

            modelBuilder.Entity("Millet.Compras.Domain.Oc.OrdenCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlmacenDestinoDefaultId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_destino_default_id");

                    b.Property<Guid>("CompradorTitularId")
                        .HasColumnType("uuid")
                        .HasColumnName("comprador_titular_id");

                    b.Property<Guid>("CondicionesPagoId")
                        .HasColumnType("uuid")
                        .HasColumnName("condiciones_pago_id");

                    b.Property<string>("ContactoProveedorEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contacto_proveedor_email");

                    b.Property<string>("ContactoProveedorNombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contacto_proveedor_nombre");

                    b.Property<string>("ContactoProveedorTelefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contacto_proveedor_telefono");

                    b.Property<bool>("CotizacionExcepcionada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cotizacion_excepcionada");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<short?>("DescuentoGlobalTipo")
                        .HasColumnType("smallint")
                        .HasColumnName("descuento_global_tipo");

                    b.Property<decimal?>("DescuentoGlobalValor")
                        .HasColumnType("numeric(15,4)")
                        .HasColumnName("descuento_global_valor");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("EncargadoComprasId")
                        .HasColumnType("uuid")
                        .HasColumnName("encargado_compras_id");

                    b.Property<bool>("EsImportacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_importacion");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset?>("FechaContabilizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_contabilizacion");

                    b.Property<DateTimeOffset>("FechaDocumento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_documento");

                    b.Property<DateTimeOffset?>("FechaEntregaEsperada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_entrega_esperada");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("folio");

                    b.Property<short>("FolioAnio")
                        .HasColumnType("smallint")
                        .HasColumnName("folio_anio");

                    b.Property<decimal>("GastosAdicionales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("gastos_adicionales");

                    b.Property<string>("InfoImportCodigoRuta")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("info_import_codigo_ruta");

                    b.Property<Guid?>("InfoImportIncotermId")
                        .HasColumnType("uuid")
                        .HasColumnName("info_import_incoterm_id");

                    b.Property<string>("InfoImportNumeroContenedor")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("info_import_numero_contenedor");

                    b.Property<string>("InfoImportNumeroPedimento")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("info_import_numero_pedimento");

                    b.Property<string>("InfoImportPaisOrigen")
                        .HasColumnType("char(2)")
                        .HasColumnName("info_import_pais_origen");

                    b.Property<string>("InfoImportSemanaEmbarque")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("info_import_semana_embarque");

                    b.Property<string>("InfoLogisticaDireccion")
                        .HasColumnType("text")
                        .HasColumnName("info_logistica_direccion");

                    b.Property<string>("InfoLogisticaInstrucciones")
                        .HasColumnType("text")
                        .HasColumnName("info_logistica_instrucciones");

                    b.Property<string>("InfoLogisticaNumeroGuia")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("info_logistica_numero_guia");

                    b.Property<Guid?>("InfoLogisticaTransportistaId")
                        .HasColumnType("uuid")
                        .HasColumnName("info_logistica_transportista_id");

                    b.Property<string>("InfoLogisticaTransportistaTexto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("info_logistica_transportista_texto");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("MXN")
                        .HasColumnName("moneda");

                    b.Property<string>("MotivoCancelacion")
                        .HasColumnType("text")
                        .HasColumnName("motivo_cancelacion");

                    b.Property<Guid?>("MotivoRechazoId")
                        .HasColumnType("uuid")
                        .HasColumnName("motivo_rechazo_id");

                    b.Property<string>("MotivoRechazoTexto")
                        .HasColumnType("text")
                        .HasColumnName("motivo_rechazo_texto");

                    b.Property<string>("MotivoSinRequisicion")
                        .HasColumnType("text")
                        .HasColumnName("motivo_sin_requisicion");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<Guid?>("OcOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("oc_origen_id");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<decimal>("Redondeo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("redondeo");

                    b.Property<string>("ReferenciaProveedor")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("referencia_proveedor");

                    b.Property<bool>("SinRequisicionPrevia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("sin_requisicion_previa");

                    b.Property<short>("SubEstadoFacturacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("sub_estado_facturacion");

                    b.Property<short>("SubEstadoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("sub_estado_pago");

                    b.Property<short>("SubEstadoRecepcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("sub_estado_recepcion");

                    b.Property<Guid>("SucursalDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_destino_id");

                    b.Property<decimal?>("TipoCambio")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("tipo_cambio");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UsoPrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("uso_principal_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_ordenes_compra");

                    b.HasIndex("InfoImportCodigoRuta")
                        .HasDatabaseName("ix_oc_ruta")
                        .HasFilter("info_import_codigo_ruta IS NOT NULL");

                    b.HasIndex("InfoImportNumeroContenedor")
                        .HasDatabaseName("ix_oc_contenedor")
                        .HasFilter("info_import_numero_contenedor IS NOT NULL");

                    b.HasIndex("InfoImportSemanaEmbarque")
                        .HasDatabaseName("ix_oc_semana")
                        .HasFilter("info_import_semana_embarque IS NOT NULL");

                    b.HasIndex("OcOrigenId")
                        .HasDatabaseName("ix_oc_origen")
                        .HasFilter("oc_origen_id IS NOT NULL");

                    b.HasIndex("EmpresaId", "CompradorTitularId")
                        .HasDatabaseName("ix_oc_empresa_comprador");

                    b.HasIndex("EmpresaId", "Estado")
                        .HasDatabaseName("ix_oc_empresa_estado");

                    b.HasIndex("EmpresaId", "FechaDocumento")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_oc_empresa_fecha");

                    b.HasIndex("EmpresaId", "ProveedorId")
                        .HasDatabaseName("ix_oc_empresa_proveedor");

                    b.HasIndex("EmpresaId", "ReferenciaProveedor")
                        .HasDatabaseName("ix_oc_referencia_proveedor")
                        .HasFilter("referencia_proveedor IS NOT NULL");

                    b.HasIndex("EmpresaId", "SucursalDestinoId", "Folio")
                        .IsUnique()
                        .HasDatabaseName("uq_ordenes_compra_folio");

                    b.HasIndex("EmpresaId", "Estado", "SubEstadoRecepcion", "SubEstadoFacturacion", "SubEstadoPago")
                        .HasDatabaseName("ix_oc_partidas_abiertas")
                        .HasFilter("estado = 3");

                    b.ToTable("ordenes_compra", "compras", t =>
                        {
                            t.HasCheckConstraint("ck_oc_estado", "estado BETWEEN 0 AND 6");

                            t.HasCheckConstraint("ck_oc_import_campos", "(es_importacion = false) OR (es_importacion = true AND info_import_incoterm_id IS NOT NULL AND info_import_pais_origen IS NOT NULL AND info_import_numero_contenedor IS NOT NULL)");

                            t.HasCheckConstraint("ck_oc_sin_rq_motivo", "sin_requisicion_previa = false OR motivo_sin_requisicion IS NOT NULL");

                            t.HasCheckConstraint("ck_oc_sub_facturacion", "sub_estado_facturacion BETWEEN 0 AND 2");

                            t.HasCheckConstraint("ck_oc_sub_pago", "sub_estado_pago BETWEEN 0 AND 2");

                            t.HasCheckConstraint("ck_oc_sub_recepcion", "sub_estado_recepcion BETWEEN 0 AND 2");

                            t.HasCheckConstraint("ck_oc_tipo_cambio", "(moneda = 'MXN' AND tipo_cambio IS NULL) OR (moneda <> 'MXN' AND tipo_cambio > 0)");
                        });
                });

            modelBuilder.Entity("Millet.Compras.Domain.Requisicion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorTerminacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_terminacion_id");

                    b.Property<Guid>("AlmacenDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_destino_id");

                    b.Property<short>("Clasificacion")
                        .HasColumnType("smallint")
                        .HasColumnName("clasificacion");

                    b.Property<Guid>("CreadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creador_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("DepartamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("departamento_id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaEntregaDeseada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega_deseada");

                    b.Property<DateTimeOffset>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_solicitud");

                    b.Property<DateTimeOffset?>("FechaTerminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_terminacion");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("folio");

                    b.Property<short>("FolioAnio")
                        .HasColumnType("smallint")
                        .HasColumnName("folio_anio");

                    b.Property<Guid?>("MotivoTerminacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("motivo_terminacion_id");

                    b.Property<string>("MotivoTerminacionTexto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_terminacion_texto");

                    b.Property<short>("Prioridad")
                        .HasColumnType("smallint")
                        .HasColumnName("prioridad");

                    b.Property<Guid?>("ProveedorSugeridoId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_sugerido_id");

                    b.Property<Guid>("RequisitanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("requisitante_id");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_requisiciones");

                    b.HasIndex("EmpresaId", "RequisitanteId")
                        .HasDatabaseName("ix_requisiciones_empresa_id_requisitante_id");

                    b.HasIndex("EmpresaId", "DepartamentoId", "Estado")
                        .HasDatabaseName("ix_requisiciones_empresa_id_departamento_id_estado");

                    b.HasIndex("EmpresaId", "DepartamentoId", "FechaSolicitud")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_requisiciones_empresa_id_departamento_id_fecha_solicitud");

                    b.HasIndex("EmpresaId", "Estado", "FechaSolicitud")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_requisiciones_empresa_id_estado_fecha_solicitud");

                    b.HasIndex("EmpresaId", "FolioAnio", "Folio")
                        .IsUnique()
                        .HasDatabaseName("ix_requisiciones_empresa_id_folio_anio_folio");

                    b.HasIndex("EmpresaId", "RequisitanteId", "FechaSolicitud")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_requisiciones_empresa_id_requisitante_id_fecha_solicitud");

                    b.ToTable("requisiciones", "compras", t =>
                        {
                            t.HasCheckConstraint("ck_requisiciones_clasificacion", "clasificacion BETWEEN 0 AND 3");

                            t.HasCheckConstraint("ck_requisiciones_estado", "estado BETWEEN 0 AND 7");

                            t.HasCheckConstraint("ck_requisiciones_prioridad", "prioridad BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Millet.Compras.Domain.UmbralAprobacionDepartamento", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("DepartamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("departamento_id");

                    b.Property<DateOnly>("VigenteDesde")
                        .HasColumnType("date")
                        .HasColumnName("vigente_desde");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("MXN")
                        .HasColumnName("moneda");

                    b.Property<decimal>("UmbralMonto")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("umbral_monto");

                    b.Property<DateOnly?>("VigenteHasta")
                        .HasColumnType("date")
                        .HasColumnName("vigente_hasta");

                    b.HasKey("EmpresaId", "DepartamentoId", "VigenteDesde")
                        .HasName("pk_umbrales_aprobacion_departamento");

                    b.ToTable("umbrales_aprobacion_departamento", "compras", t =>
                        {
                            t.HasCheckConstraint("ck_umbrales_moneda_iso", "moneda ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_umbrales_monto_no_negativo", "umbral_monto >= 0");
                        });
                });

            modelBuilder.Entity("Millet.Compras.Infrastructure.Stubs.OcBorradorStub", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("LineasJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("lineas_json");

                    b.Property<Guid>("OrigenRequisicionId")
                        .HasColumnType("uuid")
                        .HasColumnName("origen_requisicion_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_oc_borrador_stub");

                    b.HasIndex("OrigenRequisicionId")
                        .HasDatabaseName("ix_oc_borrador_stub_origen_requisicion_id");

                    b.ToTable("oc_borrador_stub", "compras");
                });

            modelBuilder.Entity("Millet.SharedKernel.Domain.Audit.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("AggregateRootId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_root_id");

                    b.Property<string>("Cambios")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cambios");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entidad");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<bool>("EsBulk")
                        .HasColumnType("boolean")
                        .HasColumnName("es_bulk");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<string>("Metadatos")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadatos");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("modulo");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operacion");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id", "Timestamp")
                        .HasName("pk_audit_log");

                    b.HasIndex("EmpresaId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_empresa_id_timestamp");

                    b.HasIndex("UsuarioId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_usuario_id_timestamp");

                    b.HasIndex("Modulo", "AggregateRootId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_modulo_aggregate_root_id_timestamp");

                    b.HasIndex("Modulo", "Entidad", "EntidadId")
                        .HasDatabaseName("ix_audit_log_modulo_entidad_entidad_id");

                    b.ToTable("audit_log", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Millet.SharedKernel.Infrastructure.Outbox.IntegrationEventOutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("IntegrationEmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_empresa_id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_integration_events_outbox");

                    b.HasIndex("IntegrationEmpresaId")
                        .HasDatabaseName("ix_integration_events_outbox_integration_empresa_id");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_integration_events_outbox_pending")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("integration_events_outbox", "compras");
                });

            modelBuilder.Entity("Millet.Compras.Domain.Autorizacion", b =>
                {
                    b.HasOne("Millet.Compras.Domain.Requisicion", null)
                        .WithMany("Autorizaciones")
                        .HasForeignKey("RequisicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_requisicion_autorizaciones_requisiciones_requisicion_id");
                });

            modelBuilder.Entity("Millet.Compras.Domain.LineaRequisicion", b =>
                {
                    b.HasOne("Millet.Compras.Domain.Requisicion", null)
                        .WithMany("Lineas")
                        .HasForeignKey("RequisicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_requisicion_lineas_requisiciones_requisicion_id");
                });

            modelBuilder.Entity("Millet.Compras.Domain.Oc.OrdenCompra", b =>
                {
                    b.HasOne("Millet.Compras.Domain.Oc.OrdenCompra", null)
                        .WithMany()
                        .HasForeignKey("OcOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_oc_origen");
                });

            modelBuilder.Entity("Millet.Compras.Domain.Requisicion", b =>
                {
                    b.Navigation("Autorizaciones");

                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
