// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Millet.Compras.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Millet.Compras.Infrastructure.Migrations
{
    [DbContext(typeof(ComprasDbContext))]
    [Migration("20260508013021_LineasYCubrimiento")]
    partial class LineasYCubrimiento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("compras")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Millet.Compras.Domain.FolioSecuencia", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_id");

                    b.Property<short>("Anio")
                        .HasColumnType("smallint")
                        .HasColumnName("anio");

                    b.Property<int>("Siguiente")
                        .HasColumnType("integer")
                        .HasColumnName("siguiente");

                    b.HasKey("EmpresaId", "SucursalId", "Anio")
                        .HasName("pk_folio_secuencias");

                    b.ToTable("folio_secuencias", "compras");
                });

            modelBuilder.Entity("Millet.Compras.Domain.LineaRequisicion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("articulo_id");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 5)
                        .HasColumnType("numeric(18,5)")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("CantidadDeAlmacen")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 5)
                        .HasColumnType("numeric(18,5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("cant_de_almacen");

                    b.Property<decimal>("CantidadDeCompra")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 5)
                        .HasColumnType("numeric(18,5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("cant_de_compra");

                    b.Property<decimal>("CantidadRecibida")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 5)
                        .HasColumnType("numeric(18,5)")
                        .HasDefaultValue(0m)
                        .HasColumnName("cant_recibida");

                    b.Property<Guid?>("CentroCostoId")
                        .HasColumnType("uuid")
                        .HasColumnName("centro_costo_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CuentaContableId")
                        .HasColumnType("uuid")
                        .HasColumnName("cuenta_contable_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateOnly?>("FechaRequerida")
                        .HasColumnType("date")
                        .HasColumnName("fecha_requerida");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notas");

                    b.Property<short>("Posicion")
                        .HasColumnType("smallint")
                        .HasColumnName("posicion");

                    b.Property<string>("Proyecto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("proyecto");

                    b.Property<Guid>("RequisicionId")
                        .HasColumnType("uuid")
                        .HasColumnName("requisicion_id");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidad_medida");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty<Dictionary<string, object>>("PrecioEstimado", "Millet.Compras.Domain.LineaRequisicion.PrecioEstimado#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("precio_estimado");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("MXN")
                                .HasColumnName("moneda");
                        });

                    b.HasKey("Id")
                        .HasName("pk_requisicion_lineas");

                    b.HasIndex("RequisicionId", "Posicion")
                        .IsUnique()
                        .HasDatabaseName("ix_requisicion_lineas_requisicion_id_posicion");

                    b.ToTable("requisicion_lineas", "compras", t =>
                        {
                            t.HasCheckConstraint("ck_requisicion_lineas_cantidad_positiva", "cantidad > 0");

                            t.HasCheckConstraint("ck_requisicion_lineas_cubrimiento_no_excede", "cant_de_almacen + cant_de_compra <= cantidad");

                            t.HasCheckConstraint("ck_requisicion_lineas_moneda_iso", "moneda ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_requisicion_lineas_recibida_no_excede_compra", "cant_recibida <= cant_de_compra");
                        });
                });

            modelBuilder.Entity("Millet.Compras.Domain.Requisicion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorTerminacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_terminacion_id");

                    b.Property<Guid>("AlmacenDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_destino_id");

                    b.Property<short>("Clasificacion")
                        .HasColumnType("smallint")
                        .HasColumnName("clasificacion");

                    b.Property<Guid>("CreadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creador_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("DepartamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("departamento_id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaEntregaDeseada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega_deseada");

                    b.Property<DateTimeOffset>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_solicitud");

                    b.Property<DateTimeOffset?>("FechaTerminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_terminacion");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("folio");

                    b.Property<short>("FolioAnio")
                        .HasColumnType("smallint")
                        .HasColumnName("folio_anio");

                    b.Property<Guid?>("MotivoTerminacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("motivo_terminacion_id");

                    b.Property<string>("MotivoTerminacionTexto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_terminacion_texto");

                    b.Property<short>("Prioridad")
                        .HasColumnType("smallint")
                        .HasColumnName("prioridad");

                    b.Property<Guid?>("ProveedorSugeridoId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_sugerido_id");

                    b.Property<Guid>("RequisitanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("requisitante_id");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_requisiciones");

                    b.HasIndex("EmpresaId", "RequisitanteId")
                        .HasDatabaseName("ix_requisiciones_empresa_id_requisitante_id");

                    b.HasIndex("EmpresaId", "DepartamentoId", "Estado")
                        .HasDatabaseName("ix_requisiciones_empresa_id_departamento_id_estado");

                    b.HasIndex("EmpresaId", "Estado", "FechaSolicitud")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_requisiciones_empresa_id_estado_fecha_solicitud");

                    b.HasIndex("EmpresaId", "FolioAnio", "Folio")
                        .IsUnique()
                        .HasDatabaseName("ix_requisiciones_empresa_id_folio_anio_folio");

                    b.ToTable("requisiciones", "compras", t =>
                        {
                            t.HasCheckConstraint("ck_requisiciones_clasificacion", "clasificacion BETWEEN 0 AND 3");

                            t.HasCheckConstraint("ck_requisiciones_estado", "estado BETWEEN 0 AND 7");

                            t.HasCheckConstraint("ck_requisiciones_prioridad", "prioridad BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Millet.SharedKernel.Domain.Audit.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Cambios")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cambios");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entidad");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<bool>("EsBulk")
                        .HasColumnType("boolean")
                        .HasColumnName("es_bulk");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<string>("Metadatos")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadatos");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("modulo");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operacion");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id", "Timestamp")
                        .HasName("pk_audit_log");

                    b.HasIndex("EmpresaId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_empresa_id_timestamp");

                    b.HasIndex("UsuarioId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_usuario_id_timestamp");

                    b.HasIndex("Modulo", "Entidad", "EntidadId")
                        .HasDatabaseName("ix_audit_log_modulo_entidad_entidad_id");

                    b.ToTable("audit_log", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Millet.Compras.Domain.LineaRequisicion", b =>
                {
                    b.HasOne("Millet.Compras.Domain.Requisicion", null)
                        .WithMany("Lineas")
                        .HasForeignKey("RequisicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_requisicion_lineas_requisiciones_requisicion_id");
                });

            modelBuilder.Entity("Millet.Compras.Domain.Requisicion", b =>
                {
                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
